# Generated by Django 5.1.7 on 2025-12-23 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypostingsetup',
            name='wip_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wip_account_setups', to='financials.g_laccount', verbose_name='WIP Account'),
        ),
    ]
