# Generated by Django 5.1.7 on 2026-03-05 18:51

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


def create_vat_posting_setup_table_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'postings_vatpostingsetup'
            """
        )
        if cursor.fetchone():
            return
    # Historical apps at 0002 do not include VATPostingSetup; use live model for DDL only when missing.
    from postings.models import VATPostingSetup

    schema_editor.create_model(VATPostingSetup)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0009_add_vat_enabled_to_general_ledger_setup"),
        ("postings", "0002_inventorypostingsetup_wip_account"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="VATPostingSetup",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "vat_percent",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                help_text="VAT percentage, e.g. 18.00",
                                max_digits=5,
                                verbose_name="VAT %",
                            ),
                        ),
                        (
                            "vat_calculation_type",
                            models.CharField(
                                choices=[
                                    ("Normal", "Normal"),
                                    ("Full VAT", "Full VAT"),
                                    ("Reverse Charge", "Reverse Charge"),
                                ],
                                default="Normal",
                                max_length=20,
                                verbose_name="VAT Calculation Type",
                            ),
                        ),
                        (
                            "vat_identifier",
                            models.CharField(
                                blank=True,
                                help_text="For grouping/reporting, e.g. VAT18.",
                                max_length=20,
                                null=True,
                                verbose_name="VAT Identifier",
                            ),
                        ),
                        (
                            "purchase_vat_account",
                            models.ForeignKey(
                                blank=True,
                                help_text="G/L account for purchase VAT (input VAT).",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="purchase_vat_postings",
                                to="financials.g_laccount",
                                verbose_name="VAT Purchase Account",
                            ),
                        ),
                        (
                            "sales_vat_account",
                            models.ForeignKey(
                                blank=True,
                                help_text="G/L account for sales VAT (output VAT).",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="sales_vat_postings",
                                to="financials.g_laccount",
                                verbose_name="VAT Sales Account",
                            ),
                        ),
                        (
                            "vat_business_posting_group",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="vat_posting_setups",
                                to="postings.vatbusinesspostinggroup",
                                verbose_name="VAT Bus. Posting Group",
                            ),
                        ),
                        (
                            "vat_product_posting_group",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="vat_posting_setups",
                                to="postings.vatproductpostinggroup",
                                verbose_name="VAT Prod. Posting Group",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "VAT Posting Setup",
                        "verbose_name_plural": "VAT Posting Setups",
                        "unique_together": {
                            ("vat_business_posting_group", "vat_product_posting_group")
                        },
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    create_vat_posting_setup_table_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
