# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import financials.enums
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('no', models.CharField(help_text='Bank Account Number', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='No.')),
                ('name', models.CharField(help_text='Name of the bank account', max_length=255, verbose_name='Name')),
                ('address', models.TextField(blank=True, help_text='Address of the bank', null=True, verbose_name='Address')),
                ('contact', models.TextField(blank=True, help_text='Contact information for the bank', null=True, verbose_name='Contact')),
                ('bank_account_no', models.CharField(blank=True, help_text='Bank account number at the bank', max_length=255, null=True, verbose_name='Bank Account No.')),
                ('bank_branch_no', models.CharField(blank=True, help_text='Bank branch number', max_length=255, null=True, verbose_name='Bank Branch No.')),
                ('min_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum balance required for this account', max_digits=15, verbose_name='Min. Balance')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountPostingGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Unique code for the bank account posting group', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('description', models.CharField(help_text='Description of the bank account posting group', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Bank Account Posting Group',
                'verbose_name_plural': 'Bank Account Posting Groups',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('entry_no', models.AutoField(help_text='Automatic entry number', primary_key=True, serialize=False, verbose_name='Entry No.')),
                ('posting_date', models.DateField(help_text='Date when the entry was posted', verbose_name='Posting Date')),
                ('document_type', models.CharField(choices=[('Payment', 'Payment'), ('Invoice', 'Invoice'), ('Credit_Memo', 'Credit Memo'), ('Finance_Charge_Memo', 'Finance Charge Memo'), ('Reminder', 'Reminder'), ('Refund', 'Refund')], default='Payment', help_text='Type of document that created this entry', max_length=50, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, help_text='Description of the transaction', null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount (positive for debit, negative for credit)', max_digits=15, verbose_name='Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be applied', max_digits=15, verbose_name='Remaining Amount')),
                ('bal_account_type', models.CharField(blank=True, choices=financials.enums.BalacingAccountType.choices, default='G/L Account', help_text='Type of balancing account', max_length=50, null=True, verbose_name='Bal. Account Type')),
                ('bal_account_no', models.CharField(blank=True, help_text='Balancing account number (based on Bal. Account Type)', max_length=255, null=True, verbose_name='Bal. Account No.')),
                ('statement_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Bank_Acc_Entry_Applied', 'Bank Acc. Entry Applied'), ('Check_Entry_Applied', 'Check Entry Applied')], default='Open', help_text='Status of bank statement reconciliation', max_length=50, verbose_name='Statement Status')),
                ('statement_no', models.CharField(blank=True, help_text='Bank statement number', max_length=50, null=True, verbose_name='Statement No.')),
                ('statement_line_no', models.IntegerField(blank=True, help_text='Line number on bank statement', null=True, verbose_name='Statement Line No.')),
                ('document_date', models.DateField(blank=True, help_text='Date of the source document', null=True, verbose_name='Document Date')),
                ('document_no', models.CharField(blank=True, help_text='Document number that created this entry', max_length=50, null=True, verbose_name='Document No.')),
                ('reversed', models.BooleanField(db_index=True, default=False, help_text='Indicates if this entry has been reversed', verbose_name='Reversed')),
                ('reversed_by_entry_no', models.IntegerField(blank=True, db_index=True, help_text='Entry number that reversed this entry', null=True, verbose_name='Reversed By Entry No.')),
                ('reversed_entry_no', models.IntegerField(blank=True, db_index=True, help_text='If this is a reversing entry, the entry number it reverses', null=True, verbose_name='Reversed Entry No.')),
                ('reversed_date', models.DateField(blank=True, help_text='Date when this entry was reversed', null=True, verbose_name='Reversal Date')),
                ('bank_account_no', models.ForeignKey(help_text='Bank account for this entry', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bank_account.bankaccount', verbose_name='Bank Account No.')),
                ('dimension_1', models.ForeignKey(blank=True, help_text='Dimension value for dimension 1', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_ledger_entries', to='dimension.dimensionvalue', verbose_name='Dimension 1')),
                ('reversed_by_user', models.ForeignKey(blank=True, help_text='User who performed the reversal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_ledger_reversals', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By User')),
                ('user', models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bank Account Ledger Entry',
                'verbose_name_plural': 'Bank Account Ledger Entries',
                'ordering': ['-posting_date', '-entry_no'],
            },
        ),
    ]
