# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountpostinggroup',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='General ledger account number for bank account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_posting_groups', to='financials.g_laccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='bankaccountledgerentry',
            name='bank_account_posting_group',
            field=models.ForeignKey(blank=True, help_text='Posting group from bank account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bank_account.bankaccountpostinggroup', verbose_name='Bank Acc. Posting Group'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_posting_group',
            field=models.ForeignKey(blank=True, help_text='Posting group for this bank account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='bank_account.bankaccountpostinggroup', verbose_name='Bank Acc. Posting Group'),
        ),
        migrations.AddIndex(
            model_name='bankaccountpostinggroup',
            index=models.Index(fields=['code'], name='bank_accoun_code_8f37ca_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountledgerentry',
            index=models.Index(fields=['bank_account_no', 'posting_date'], name='bank_accoun_bank_ac_b4a06b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountledgerentry',
            index=models.Index(fields=['document_no'], name='bank_accoun_documen_00ebd7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountledgerentry',
            index=models.Index(fields=['statement_no', 'statement_line_no'], name='bank_accoun_stateme_6c13b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountledgerentry',
            index=models.Index(fields=['reversed'], name='bank_accoun_reverse_6ec604_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountledgerentry',
            index=models.Index(fields=['reversed_entry_no'], name='bank_accoun_reverse_2cf93e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['no'], name='bank_accoun_no_0fb0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_account_posting_group'], name='bank_accoun_bank_ac_132f13_idx'),
        ),
    ]
