# Generated by Django 5.1.7 on 2026-02-27 15:10

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_dimension_set_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _pg_column_exists(
            cursor, "bank_account_bankaccountledgerentry", "dimension_set_id"
        ):
            cursor.execute(
                """
                ALTER TABLE bank_account_bankaccountledgerentry
                ADD COLUMN dimension_set_id bigint NULL
                REFERENCES dimension_dimensionset(id)
                ON DELETE SET NULL
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0002_initial"),
        ("dimension", "0004_add_dimension_set_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="bankaccountledgerentry",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_account_ledger_entries",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AlterField(
                    model_name="bankaccountledgerentry",
                    name="dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_account_ledger_entries",
                        to="dimension.dimensionvalue",
                        verbose_name="Dimension 1",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_dimension_set_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
