# Generated by Django 5.1.7 on 2026-02-27 18:25

import importlib

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def ensure_dimension_value_integer_pk(apps, schema_editor):
    """
    bank_account ledger FK targets dimension_dimensionvalue(id). Some tenants still
    have code-only PK (Dimension 0003 never applied to DB). Run that migration's data
    step when id is missing.
    """
    with schema_editor.connection.cursor() as cursor:
        if _pg_column_exists(cursor, "dimension_dimensionvalue", "id"):
            return
    mod = importlib.import_module("dimension.migrations.0003_dimension_id_pk")
    mod.migrate_dimension_pk_to_id(apps, schema_editor)


def migrate_bank_ledger_global_dimension_1(apps, schema_editor):
    table = "bank_account_bankaccountledgerentry"
    with schema_editor.connection.cursor() as cursor:
        has_old = _pg_column_exists(cursor, table, "dimension_1_id")
        has_new = _pg_column_exists(cursor, table, "global_dimension_1_id")
        if has_old and not has_new:
            cursor.execute(
                f"ALTER TABLE {table} RENAME COLUMN dimension_1_id TO global_dimension_1_id"
            )
        elif has_old and has_new:
            cursor.execute(f"ALTER TABLE {table} DROP COLUMN dimension_1_id CASCADE")
        elif not has_new:
            cursor.execute(
                f"""
                ALTER TABLE {table}
                ADD COLUMN global_dimension_1_id bigint NULL
                REFERENCES dimension_dimensionvalue(id)
                ON DELETE RESTRICT
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0003_add_dimension_set_to_ledger_models"),
        ("dimension", "0003_dimension_id_pk"),
        ("dimension", "0004_add_dimension_set_models"),
    ]

    operations = [
        migrations.RunPython(ensure_dimension_value_integer_pk, noop_reverse),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="bankaccountledgerentry",
                    name="dimension_1",
                ),
                migrations.AddField(
                    model_name="bankaccountledgerentry",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_account_ledger_entries",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    migrate_bank_ledger_global_dimension_1,
                    noop_reverse,
                ),
            ],
        ),
    ]
