# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import django.utils.timezone
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Unique code (e.g., SALES_CENTER, DISPENSER_CENTER)', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Sales Role Center', 'Dispenser Center')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this role center is for')),
                ('modules', models.JSONField(blank=True, default=list, help_text="List of module codes to show, e.g., ['sales', 'customers', 'items']")),
                ('features', models.JSONField(blank=True, default=dict, help_text='\n        Optional: Features per module, e.g.:\n        {\n          "sales": ["dashboard", "invoices", "history"],\n          "customers": ["list", "create", "reports"]\n        }\n        ')),
                ('dashboard_widgets', models.JSONField(blank=True, default=list, help_text="Widget IDs to show on dashboard, e.g., ['sales_chart', 'top_customers']")),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this role center')),
            ],
            options={
                'verbose_name': 'Role Center',
                'verbose_name_plural': 'Role Centers',
                'db_table': 'authentication_rolecenter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('can_see_buying_price', models.BooleanField(default=True, help_text='Allow user to see buying/cost prices on items')),
                ('can_see_profit_margin', models.BooleanField(default=True, help_text='Allow user to see profit margins and markup percentages')),
                ('can_see_item_cost', models.BooleanField(default=True, help_text='Allow user to see item cost in transactions')),
                ('can_post_previous_dates', models.BooleanField(default=True, help_text='Allow user to post sales or purchases for previous dates')),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this user's setup")),
            ],
            options={
                'verbose_name': 'User Setup',
                'verbose_name_plural': 'User Setups',
                'db_table': 'authentication_usersetup',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_1', models.ForeignKey(blank=True, db_column='dimension_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimension_1_entries', to='dimension.dimensionvalue')),
                ('dimensions', models.ManyToManyField(blank=True, db_column='dimensions', related_name='dimension_entries', to='dimension.dimensionvalue')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='authentication.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='role_center',
            field=models.ForeignKey(blank=True, help_text='Role Center that defines which modules this role can access (like Business Central)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to='authentication.rolecenter'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Unique code for the user group (e.g., SALES_DEPT, WAREHOUSE_TEAM)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the user group', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of this user group's purpose")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user group is active')),
                ('default_profile', models.ForeignKey(blank=True, help_text='Default role assigned to users in this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups_default', to='authentication.role')),
                ('members', models.ManyToManyField(blank=True, help_text='Users who belong to this group', related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'db_table': 'authentication_usergroup',
                'ordering': ['name'],
            },
        ),
    ]
