# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='permission_sets',
            field=models.ManyToManyField(blank=True, help_text='Permission sets assigned to this user group', related_name='user_groups', to='permissions.permissionset'),
        ),
        migrations.AddField(
            model_name='usersetup',
            name='user',
            field=models.OneToOneField(help_text='User this setup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='setup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='authenticat_created_381ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['system_id'], name='authenticat_system__0e2184_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='authenticat_created_901291_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['system_id'], name='authenticat_system__712178_idx'),
        ),
    ]
