# Generated by Django 5.1.7 on 2025-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_can_post_previous_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetup',
            name='can_reverse_purchase_invoice',
            field=models.BooleanField(default=True, help_text='Allow user to reverse posted purchase invoices'),
        ),
    ]
