# Generated by Django 5.1.7 on 2026-01-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usersetup_can_reverse_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetup',
            name='can_reverse_sales_invoice',
            field=models.BooleanField(default=True, help_text='Allow user to reverse posted sales invoices'),
        ),
    ]
