# Generated by Django 5.1.7 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usersetup_can_reverse_sales_invoice'),
        ('dimension', '0004_add_dimension_set_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dimension_1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, db_column='dimension_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_global_dim_1_entries', to='dimension.dimensionvalue'),
        ),
    ]
