# Generated by Django 5.1.7 on 2026-02-24 19:08

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('file', models.FileField(max_length=255, upload_to='document_attachments/%Y/%m/', verbose_name='File')),
                ('name', models.CharField(blank=True, help_text='Optional display name; defaults to filename', max_length=255, verbose_name='Display name')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_attachments', to='purchases.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'db_table': 'purchases_documentattachment',
                'ordering': ('-created_at',),
            },
        ),
    ]
