# Generated by Django 5.1.7 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def migrate_purchases_dimension_columns(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:

        def reconcile_rename(table):
            has_old = _pg_column_exists(cursor, table, "dimension_1_id")
            has_new = _pg_column_exists(cursor, table, "global_dimension_1_id")
            if has_old and not has_new:
                cursor.execute(
                    f'ALTER TABLE {table} RENAME COLUMN dimension_1_id TO global_dimension_1_id'
                )
            elif has_old and has_new:
                cursor.execute(
                    f"ALTER TABLE {table} DROP COLUMN dimension_1_id CASCADE"
                )

        reconcile_rename("purchases_purchaseinvoiceline")
        reconcile_rename("purchases_vendorledger")

        if _pg_column_exists(cursor, "purchases_detailedvendorledgerentry", "dimension_1_id"):
            cursor.execute(
                "ALTER TABLE purchases_detailedvendorledgerentry DROP COLUMN dimension_1_id CASCADE"
            )
        if not _pg_column_exists(
            cursor, "purchases_detailedvendorledgerentry", "global_dimension_1_id"
        ):
            cursor.execute(
                """
                ALTER TABLE purchases_detailedvendorledgerentry
                ADD COLUMN global_dimension_1_id bigint NULL
                REFERENCES dimension_dimensionvalue(id)
                ON DELETE RESTRICT
                """
            )

        if _pg_column_exists(cursor, "purchases_purchasecreditmemoline", "dimension_1_id"):
            cursor.execute(
                "ALTER TABLE purchases_purchasecreditmemoline DROP COLUMN dimension_1_id CASCADE"
            )
        if not _pg_column_exists(
            cursor, "purchases_purchasecreditmemoline", "global_dimension_1_id"
        ):
            cursor.execute(
                """
                ALTER TABLE purchases_purchasecreditmemoline
                ADD COLUMN global_dimension_1_id bigint NULL
                REFERENCES dimension_dimensionvalue(id)
                ON DELETE CASCADE
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0004_add_dimension_set_models"),
        ("purchases", "0003_add_dimension_set_to_ledger_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="purchaseinvoiceline",
                    old_name="dimension_1",
                    new_name="global_dimension_1",
                ),
                migrations.RenameField(
                    model_name="vendorledger",
                    old_name="dimension_1",
                    new_name="global_dimension_1",
                ),
                migrations.RemoveField(
                    model_name="detailedvendorledgerentry",
                    name="dimension_1",
                ),
                migrations.RemoveField(
                    model_name="purchasecreditmemoline",
                    name="dimension_1",
                ),
                migrations.AddField(
                    model_name="detailedvendorledgerentry",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Global Dimension 1 value",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_detailed_entries",
                        to="dimension.dimensionvalue",
                    ),
                ),
                migrations.AddField(
                    model_name="purchasecreditmemoline",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_credit_memo_lines",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    migrate_purchases_dimension_columns,
                    noop_reverse,
                ),
            ],
        ),
    ]
