# Generated by Django 5.1.7 on 2026-06-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('caption', models.CharField(max_length=200)),
                ('source_table', models.CharField(max_length=200)),
                ('page_type', models.CharField(choices=[('List', 'List'), ('Card', 'Card'), ('Document', 'Document'), ('Journal', 'Journal'), ('Worksheet', 'Worksheet')], default='List', max_length=20)),
                ('editable', models.BooleanField(default=True)),
                ('insert_allowed', models.BooleanField(default=True)),
                ('delete_allowed', models.BooleanField(default=True)),
                ('modify_allowed', models.BooleanField(default=True)),
                ('context_filter_field', models.CharField(blank=True, max_length=200)),
                ('context_key_field', models.CharField(blank=True, max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('list_exclude_field', models.CharField(blank=True, max_length=200)),
                ('list_exclude_values', models.TextField(blank=True)),
                ('title_field', models.CharField(blank=True, max_length=200)),
                ('card_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_pages', to='pages.page')),
                ('header_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_pages', to='pages.page')),
            ],
            options={
                'db_table': 'page_engine_page',
                'ordering': ['page_id'],
            },
        ),
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmation_message', models.TextField(blank=True, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=500, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_relative_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ribbon_tab', models.CharField(blank=True, max_length=100, null=True)),
                ('visible_when_field', models.CharField(blank=True, max_length=200, null=True)),
                ('visible_when_values', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='pages.page')),
            ],
            options={
                'db_table': 'page_engine_action',
                'ordering': ['action_id'],
            },
        ),
        migrations.CreateModel(
            name='PageControl',
            fields=[
                ('page_control_id', models.AutoField(primary_key=True, serialize=False)),
                ('control_type', models.CharField(choices=[('Group', 'Group'), ('SubPage', 'SubPage'), ('Repeater', 'Repeater'), ('FactBox', 'FactBox')], default='Repeater', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('source_table', models.CharField(max_length=200)),
                ('show_caption', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_controls', to='pages.page')),
            ],
            options={
                'db_table': 'page_engine_control',
                'ordering': ['page_control_id'],
            },
        ),
        migrations.CreateModel(
            name='PageControlField',
            fields=[
                ('page_control_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('Text', 'Text'), ('Integer', 'Integer'), ('Decimal', 'Decimal'), ('Boolean', 'Boolean'), ('Date', 'Date'), ('DateTime', 'DateTime'), ('Enum', 'Enum'), ('Option', 'Option'), ('Code', 'Code'), ('Image', 'Image'), ('File', 'File'), ('Password', 'Password')], default='Text', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('primary_key', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('tab_index', models.IntegerField(default=0)),
                ('tooltip', models.CharField(blank=True, max_length=500, null=True)),
                ('enum_values', models.TextField(blank=True, null=True)),
                ('no_series_code', models.CharField(blank=True, max_length=50, null=True)),
                ('has_lookup_page', models.BooleanField(default=False)),
                ('has_drill_down_page', models.BooleanField(default=False)),
                ('has_table_relation', models.BooleanField(default=False)),
                ('related_table', models.CharField(blank=True, max_length=200, null=True)),
                ('related_field', models.CharField(blank=True, max_length=200, null=True)),
                ('related_display_field', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_context_field', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_context_default', models.CharField(blank=True, max_length=200, null=True)),
                ('freeze_column', models.BooleanField(default=False)),
                ('visible_when_field', models.CharField(blank=True, max_length=200, null=True)),
                ('visible_when_values', models.TextField(blank=True, null=True)),
                ('drill_down_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page')),
                ('lookup_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pages.page')),
                ('page_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pages.pagecontrol')),
            ],
            options={
                'db_table': 'page_engine_field',
                'ordering': ['tab_index', 'page_control_field_id'],
            },
        ),
    ]
