# Generated by Django 5.1.7 on 2026-06-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagecontrol_part_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontrol',
            options={'ordering': ['tab_index', 'page_control_id']},
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_aggregate',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average'), ('max', 'Max'), ('min', 'Min')], default='count', help_text='Aggregation function for Cue value', max_length=20),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_aggregate_field',
            field=models.CharField(blank=True, default='', help_text='Field to sum/avg/max/min (blank = count rows)', max_length=100),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_filter_field',
            field=models.CharField(blank=True, default='', help_text='Field to filter on for this Cue (e.g. status)', max_length=100),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_filter_value',
            field=models.CharField(blank=True, default='', help_text='Value to filter by (e.g. Open)', max_length=100),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_source_table',
            field=models.CharField(blank=True, default='', help_text='Model to aggregate for this CueGroup/Cue/Headline', max_length=100),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='cue_style',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('Favorable', 'Favorable (green)'), ('Unfavorable', 'Unfavorable (red)'), ('Ambiguous', 'Ambiguous (yellow)'), ('Subordinate', 'Subordinate (grey)')], default='', help_text='Visual style of the Cue tile', max_length=20),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='drill_down_page',
            field=models.ForeignKey(blank=True, help_text='List page to open when user clicks this Cue tile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cue_drill_down_source', to='pages.page'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='headline_template',
            field=models.CharField(blank=True, default='', help_text='Template for Headline control. Use {value} for computed value, {period} for time period. Example: "The biggest sales order was {value}"', max_length=500),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='max_records',
            field=models.IntegerField(default=5, help_text='For RoleCenter Part controls: max rows to return'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='parent_control',
            field=models.ForeignKey(blank=True, help_text='Parent CueGroup for Cue controls', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.pagecontrol'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='tab_index',
            field=models.IntegerField(default=0, help_text='Display/ordering position of this control within its page'),
        ),
        migrations.AddField(
            model_name='pagecontrolfield',
            name='threshold_danger',
            field=models.IntegerField(blank=True, help_text='Value at which Cue turns red (danger)', null=True),
        ),
        migrations.AddField(
            model_name='pagecontrolfield',
            name='threshold_warning',
            field=models.IntegerField(blank=True, help_text='Value at which Cue turns yellow (warning)', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('List', 'List'), ('Card', 'Card'), ('Document', 'Document'), ('ListPart', 'ListPart'), ('Journal', 'Journal'), ('Worksheet', 'Worksheet'), ('RoleCenter', 'Role Center')], default='List', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecontrol',
            name='control_type',
            field=models.CharField(choices=[('Group', 'Group'), ('SubPage', 'SubPage'), ('Repeater', 'Repeater'), ('FactBox', 'FactBox'), ('Part', 'Part'), ('CueGroup', 'Cue Group'), ('Cue', 'Cue'), ('Headline', 'Headline')], default='Repeater', max_length=20),
        ),
    ]
