# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(help_text='Descriptive name for this scheduled report', max_length=255, verbose_name='Report Name')),
                ('report_type', models.CharField(choices=[('daily_profit', 'Daily Profit Report'), ('weekly_summary', 'Weekly Summary Report'), ('monthly_summary', 'Monthly Summary Report'), ('product_profitability', 'Product Profitability Report'), ('expense_breakdown', 'Expense Breakdown Report')], max_length=50, verbose_name='Report Type')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='Frequency')),
                ('recipients', models.JSONField(help_text='List of email addresses to send the report to', verbose_name='Recipients')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='pdf', max_length=10, verbose_name='Export Format')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Stored filter parameters (date ranges, categories, etc.)', verbose_name='Filters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run', models.DateTimeField(verbose_name='Next Run')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='Report Type')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('filters_applied', models.JSONField(help_text='Filters used for this report generation', verbose_name='Filters Applied')),
                ('export_format', models.CharField(blank=True, help_text='Format if exported (pdf, csv, excel)', max_length=10, null=True, verbose_name='Export Format')),
                ('execution_time_ms', models.IntegerField(help_text='Time taken to generate the report', verbose_name='Execution Time (ms)')),
                ('cached', models.BooleanField(default=False, help_text='Whether data was served from cache', verbose_name='Cached')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_logs', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='reports.scheduledreport', verbose_name='Scheduled Report')),
            ],
            options={
                'verbose_name': 'Report Log',
                'verbose_name_plural': 'Report Logs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['report_type'], name='reports_sch_report__47f5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['frequency'], name='reports_sch_frequen_794f61_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['is_active', 'next_run'], name='reports_sch_is_acti_a9ed7b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['created_by'], name='reports_sch_created_d5c78e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['report_type'], name='reports_rep_report__bbfb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['generated_by'], name='reports_rep_generat_f2ed58_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['generated_at'], name='reports_rep_generat_8c2ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportlog',
            index=models.Index(fields=['scheduled_report'], name='reports_rep_schedul_b28aff_idx'),
        ),
    ]
