# Generated by Django 5.1.7 on 2026-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
