# Generated by Django 5.1.7 on 2026-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0006_add_room_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
