# Generated by Django 5.1.7 on 2026-03-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0010_roomamenity_drop_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomamenity',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique amenity code (e.g. WIFI, AC)', max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
