# Generated by Django 5.1.7 on 2026-05-08 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('all', 'All platforms')], db_index=True, default='android', max_length=10)),
                ('version_name', models.CharField(help_text='Human-readable version (e.g. 1.2.0). Shown in the update modal.', max_length=30)),
                ('build_number', models.PositiveIntegerField(help_text='Android versionCode / iOS CFBundleVersion integer. This is the LATEST build being released.')),
                ('min_required_build', models.PositiveIntegerField(default=0, help_text='Any installed build BELOW this number is force-blocked immediately (no grace period). Set to 0 to disable hard minimum.')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='How many days after released_at before a soft update becomes a hard block. During this window the update modal is dismissible.')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this version was released. Grace period is counted from here.')),
                ('apk_file', models.FileField(blank=True, help_text='Upload the APK directly. Leave blank if using an external download_url.', null=True, upload_to='app_versions/')),
                ('download_url', models.URLField(blank=True, help_text='External download or landing page URL. If blank and apk_file is set, the APK file URL is used. If both blank, falls back to settings.APP_LANDING_PAGE_URL.')),
                ('release_notes', models.TextField(blank=True, help_text="What's new in this version. Shown in the update modal.")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active versions are returned by the API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App version',
                'verbose_name_plural': 'App versions',
                'db_table': 'app_updates_appversion',
                'ordering': ['-build_number'],
            },
        ),
    ]
