# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the permission set', max_length=100)),
                ('code', models.CharField(help_text='Unique code for the permission set', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this permission set allows')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission set is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Set',
                'verbose_name_plural': 'Permission Sets',
                'db_table': 'permissions_permissionset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionSetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False, help_text='Allow reading this object')),
                ('insert_permission', models.BooleanField(default=False, help_text='Allow creating new records')),
                ('modify_permission', models.BooleanField(default=False, help_text='Allow modifying existing records')),
                ('delete_permission', models.BooleanField(default=False, help_text='Allow deleting records')),
                ('execute_permission', models.BooleanField(default=False, help_text='Allow executing this object')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_object', models.ForeignKey(help_text='The application object this permission applies to', on_delete=django.db.models.deletion.CASCADE, to='base.objects')),
                ('permissionset', models.ForeignKey(help_text='The permission set this line belongs to', on_delete=django.db.models.deletion.CASCADE, to='permissions.permissionset')),
            ],
            options={
                'verbose_name': 'Permission Set Line',
                'verbose_name_plural': 'Permission Set Lines',
                'db_table': 'permissions_permissionsetline',
                'ordering': ['application_object__object_name'],
                'unique_together': {('permissionset', 'application_object')},
            },
        ),
    ]
