# Generated by Django 5.1.7 on 2025-12-12 02:59

import company.models
import django.db.models.deletion
import django.utils.timezone
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_path', models.TextField(help_text='SVG path data for the icon', verbose_name='SVG path data for the icon')),
                ('icon_type', models.CharField(choices=[('outline', 'Outline'), ('solid', 'Solid')], default='outline', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Category',
                'verbose_name_plural': 'Business Categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('description', models.CharField(max_length=100)),
                ('icon_path', models.TextField(help_text='SVG path data for the icon', verbose_name='SVG path data for the icon')),
                ('icon_type', models.CharField(choices=[('outline', 'Outline'), ('solid', 'Solid')], default='outline', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Objective',
                'verbose_name_plural': 'Business Objectives',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('domain_url', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, default='company_logos/default.png', null=True, upload_to='company_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('tin', models.CharField(default='1234567890', help_text='Tax Identification Number', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('onboarding_data', models.JSONField(default=dict)),
                ('enabled_modules', models.JSONField(default=list, help_text="List of enabled module identifiers (e.g., ['pos', 'hotel'])")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(choices=[('Standard Plan', 'STANDARD'), ('Multi-Branch Plan', 'MULTI_BRANCH'), ('Premium Plan with EFRIS', 'PREMIUM')], max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Monthly price in UGX')),
                ('annual_price', models.PositiveIntegerField(help_text='Annual price in UGX')),
                ('trial_period', models.IntegerField(default=30, help_text='Trial period in days')),
                ('max_products', models.IntegerField(blank=True, help_text='Maximum number of products allowed (null means unlimited)', null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this plan', null=True)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order in which plans should be displayed')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ZentroStarterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zentro Starter 3 Months Free', max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=company.models.get_default_offer_end_date)),
                ('is_active', models.BooleanField(default=True)),
                ('free_months', models.IntegerField(default=3)),
                ('device_price', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10)),
                ('device_video', models.FileField(blank=True, help_text='Video demonstration of the device (MP4, WebM, or MOV)', null=True, upload_to='device_videos/')),
                ('video_description', models.TextField(blank=True, help_text='Description of what the video shows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zentro Starter Offer',
                'verbose_name_plural': 'Zentro Starter Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money')], default='stripe', max_length=50)),
                ('method_type', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=100)),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('gateway_payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_fingerprint', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money')], default='stripe', max_length=50)),
                ('reference_number', models.CharField(max_length=10, unique=True)),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('billing_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.paymentmethod')),
            ],
            options={
                'verbose_name': 'Billing History',
                'verbose_name_plural': 'Billing Histories',
                'ordering': ['-billing_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Free Trial', 'Free Trial'), ('Standard Plan', 'Standard Plan'), ('Multi-Branch Plan', 'Multi-Branch Plan'), ('Premium Plan with EFRIS', 'Premium Plan with EFRIS'), ('Starter Pack', 'Starter Pack')], max_length=50)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('pending', 'pending'), ('active', 'active'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='trial', max_length=20)),
                ('subscription_start_date', models.DateField(default=django.utils.timezone.now)),
                ('subscription_end_date', models.DateField()),
                ('trial_period_end_date', models.DateField(default=company.models.get_trial_end_date)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money')], default='stripe', max_length=50)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('is_trial', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='ZentroStarterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for the starter offer', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100)),
                ('device_included', models.BooleanField(default=True)),
                ('free_months_earned', models.IntegerField(default=3)),
                ('offer_days_remaining_at_payment', models.IntegerField(blank=True, help_text='Days remaining on offer when payment was made', null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('free_period_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('active', 'Subscription Active'), ('free_period_ended', 'Free Period Ended'), ('expired', 'Subscription Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='starter_orders', to='company.company')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='company.zentrostarteroffer')),
            ],
            options={
                'verbose_name': 'Zentro Starter Order',
                'verbose_name_plural': 'Zentro Starter Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOnBoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('company_size', models.CharField(choices=[('2 ~ 10 Members', '2 ~ 10 Members'), ('11 ~ 50 Members', '11 ~ 50 Members'), ('51 ~ 200 Members', '51 ~ 200 Members'), ('201 ~ 500 Members', '201 ~ 500 Members')], max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('business_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.businesscategory')),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.businessobjective')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='company_com_created_c78237_idx'), models.Index(fields=['system_id'], name='company_com_system__415fc6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['created_at'], name='company_pay_created_9d08c3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['system_id'], name='company_pay_system__e2b054_idx'),
        ),
    ]
