# Generated by Django 5.1.7 on 2025-12-15 07:03

import django.db.models.deletion
import django.utils.timezone
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zentrostarteroffer',
            name='allows_installments',
            field=models.BooleanField(default=True, help_text='Allow customers to pay in installments'),
        ),
        migrations.AddField(
            model_name='zentrostarteroffer',
            name='default_installment_count',
            field=models.IntegerField(default=4, help_text='Default number of installments if not specified'),
        ),
        migrations.AddField(
            model_name='zentrostarteroffer',
            name='payment_plan',
            field=models.CharField(choices=[('one_time', 'One-Time Payment'), ('installments', 'Installment Plan')], default='one_time', help_text='Default payment plan for this offer', max_length=20),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='installment_schedule',
            field=models.JSONField(blank=True, default=dict, help_text="Stores planned installment amounts and due dates. Format: {'installments': [{'amount': 200000, 'due_date': '2024-02-01', 'status': 'pending'}, ...]}"),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='next_receipt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='payment_plan',
            field=models.CharField(choices=[('one_time', 'One-Time Payment'), ('installments', 'Installment Plan')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='receipt_prefix',
            field=models.CharField(default='STP', max_length=10),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zentrostarterorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount due for the starter pack', max_digits=10),
        ),
        migrations.AlterField(
            model_name='zentrostarterorder',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for the starter offer (deprecated - use amount_paid)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ZentroStarterInstallmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('reminder_type', models.CharField(choices=[('payment_due', 'Payment Due Reminder'), ('overdue', 'Overdue Payment Notice'), ('final_notice', 'Final Notice')], default='payment_due', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='When this reminder was scheduled to be sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this reminder was actually sent', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether reminder email was sent')),
                ('sms_sent', models.BooleanField(default=False, help_text='Whether reminder SMS was sent')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this reminder')),
                ('order', models.ForeignKey(help_text='The starter pack order this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='company.zentrostarterorder')),
            ],
            options={
                'verbose_name': 'Installment Reminder',
                'verbose_name_plural': 'Installment Reminders',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ZentroStarterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (Card)'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='stripe', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(help_text='Internal reference number for this payment', max_length=100, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_money_number', models.CharField(blank=True, help_text='Mobile money phone number', max_length=20)),
                ('mobile_money_provider', models.CharField(blank=True, help_text='Mobile money provider (MTN, Airtel, etc.)', max_length=20)),
                ('mobile_money_reference', models.CharField(blank=True, help_text='Mobile money transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('receipt_number', models.CharField(help_text='Receipt number (STP-001, STP-002, etc.)', max_length=50, unique=True)),
                ('invoice_pdf_path', models.CharField(blank=True, help_text='Path to generated PDF receipt', max_length=500, null=True)),
                ('is_confirmed', models.BooleanField(default=True, help_text='Whether this payment is confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False, help_text='Whether receipt email was sent')),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='User who confirmed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The starter pack order this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='company.zentrostarterorder')),
                ('received_by', models.ForeignKey(blank=True, help_text='User who registered this payment (for manual payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starter Pack Payment',
                'verbose_name_plural': 'Starter Pack Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
