# Generated by Django 5.1.7 on 2025-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_zentrostarteroffer_allows_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zentrostarteroffer',
            name='show_time_limit',
            field=models.BooleanField(default=True, help_text='Show time limit badge (days remaining) on frontend'),
        ),
        migrations.AlterField(
            model_name='zentrostarteroffer',
            name='name',
            field=models.CharField(default='Zentro Starter', max_length=100),
        ),
    ]
