# Generated by Django 5.1.7 on 2025-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_zentrostarteroffer_show_time_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zentrostarterorder',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='zentrostarteroffer',
            name='free_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='zentrostarterorder',
            name='free_months_earned',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='zentrostarterpayment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Receipt number (STP-001, STP-002, etc.) - Auto-generated if not provided', max_length=50, null=True, unique=True),
        ),
    ]
