# Generated by Django 5.1.7 on 2025-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_make_receipt_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zentrostarterpayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Internal reference number for this payment - Auto-generated if not provided', max_length=100, null=True, unique=True),
        ),
    ]
