# Generated by Django 5.1.7 on 2025-12-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_make_receipt_fields_optional_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for the company. Defaults to company name if not set.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Phone number(s). Can include multiple numbers separated by | (e.g., +256 775 307070 | +256 744 307070)', max_length=255),
        ),
    ]
