# Generated by Django 5.1.7 on 2026-02-19 17:51

import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_add_display_name_website_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Monthly price in UGX')),
                ('description', models.TextField(blank=True)),
                ('is_per_unit', models.BooleanField(default=False, help_text='If True, price is per unit (e.g. per extra user)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Add-On',
                'verbose_name_plural': 'Add-Ons',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='pricing',
            name='name',
            field=models.CharField(choices=[('Standard Plan', 'STANDARD'), ('Multi-Branch Plan', 'MULTI_BRANCH'), ('Premium Plan with EFRIS', 'PREMIUM'), ('Starter', 'STARTER'), ('Business', 'BUSINESS'), ('Pro', 'PRO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Free Trial', 'Free Trial'), ('Standard Plan', 'Standard Plan'), ('Multi-Branch Plan', 'Multi-Branch Plan'), ('Premium Plan with EFRIS', 'Premium Plan with EFRIS'), ('Starter Pack', 'Starter Pack'), ('Starter', 'Starter'), ('Business', 'Business'), ('Pro', 'Pro')], max_length=50),
        ),
    ]
