# Generated by Django 5.1.7 on 2026-03-09 09:26

import company.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_add_addon_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_billing_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money'), ('manual_mobile_money', 'Manual Mobile Money')], default='stripe', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending_verification', 'Pending Verification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='enabled_modules',
            field=models.JSONField(default=company.models.get_default_enabled_modules, help_text="List of enabled module identifiers (e.g., ['pos', 'hotel']). POS module is required and enabled by default."),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money'), ('manual_mobile_money', 'Manual Mobile Money')], default='stripe', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mobile_money', 'Mobile Money'), ('manual_mobile_money', 'Manual Mobile Money')], default='stripe', max_length=50),
        ),
        migrations.CreateModel(
            name='TrialEndReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('3_days', '3 Days Before Trial End'), ('1_day', '1 Day Before Trial End')], max_length=20)),
                ('trial_end_date', models.DateField(help_text='The trial end date this reminder was for')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this reminder was sent')),
                ('source', models.CharField(choices=[('subscription', 'Subscription'), ('starter_order', 'Starter Order')], help_text='Subscription or ZentroStarterOrder', max_length=20)),
                ('source_id', models.PositiveIntegerField(help_text='ID of Subscription or ZentroStarterOrder')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_end_reminders', to='company.company')),
            ],
            options={
                'verbose_name': 'Trial End Reminder',
                'verbose_name_plural': 'Trial End Reminders',
                'ordering': ['-sent_at'],
                'unique_together': {('company', 'reminder_type', 'trial_end_date', 'source', 'source_id')},
            },
        ),
    ]
