# Generated by Django 5.1.7 on 2026-03-09 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_billinghistory_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingExpiryReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end_date', models.DateField(help_text='Access period end date (billing_date + 30)')),
                ('days_remaining', models.IntegerField(help_text='Days until expiry when sent')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_reminders', to='company.billinghistory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_expiry_reminders', to='company.company')),
            ],
            options={
                'verbose_name': 'Billing Expiry Reminder',
                'verbose_name_plural': 'Billing Expiry Reminders',
                'ordering': ['-sent_at'],
            },
        ),
    ]
