# Generated by Django 5.1.7 on 2026-03-09 12:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_source_id(apps, schema_editor):
    """Backfill source_id for existing rows with billing_history."""
    BillingExpiryReminder = apps.get_model("company", "BillingExpiryReminder")
    for r in BillingExpiryReminder.objects.filter(billing_history__isnull=False):
        r.source_id = r.billing_history_id
        r.save(update_fields=["source_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_add_billing_expiry_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingexpiryreminder',
            name='source',
            field=models.CharField(choices=[('billing_history', 'Billing History'), ('subscription', 'Subscription Trial'), ('starter_order', 'Starter Order')], default='billing_history', max_length=20),
        ),
        migrations.AddField(
            model_name='billingexpiryreminder',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingexpiryreminder',
            name='billing_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expiry_reminders', to='company.billinghistory'),
        ),
        migrations.AlterField(
            model_name='billingexpiryreminder',
            name='period_end_date',
            field=models.DateField(help_text='Access period end date (billing_date + 30 or trial/free period end)'),
        ),
        migrations.RunPython(backfill_source_id, migrations.RunPython.noop),
    ]
