# Generated by Django 5.1.7 on 2026-03-11 20:46

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_add_included_modules_and_module_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enabled_modules',
            field=models.JSONField(default=company.models.get_default_enabled_modules, help_text='Computed list of enabled module identifiers. Auto-populated from subscription plan + overrides.'),
        ),
    ]
