# Generated by Django 5.1.7 on 2026-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_company_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_limit_override',
            field=models.PositiveIntegerField(blank=True, help_text='Admin waiver: additional users beyond plan + purchased. E.g. 5 = 5 extra users allowed. Null = no waiver.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_users_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Extra users purchased via add-on (accumulated from verified payments)'),
        ),
    ]
