# Generated by Django 5.1.7 on 2026-03-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_billingexpiryreminder_reminder_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='schema_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
