# Generated by Django 5.1.7 on 2025-12-12 02:59

import financials.enums
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G_LAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('no', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='No.')),
                ('name', models.CharField(max_length=255)),
                ('indentation', models.IntegerField(default=0)),
                ('income_balance', models.CharField(blank=True, choices=[('Income Statement', 'Income Statement'), ('Balance Sheet', 'Balance Sheet')], max_length=255, null=True, verbose_name='Income/Balance')),
                ('accountcategory', models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Expense', 'Expense')], max_length=255, null=True, verbose_name='Account Category')),
                ('debit_credit', models.CharField(blank=True, choices=[('Both', 'Both'), ('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Debit/Credit')),
                ('accounttype', models.CharField(blank=True, choices=[('Posting', 'Posting'), ('Heading', 'Heading'), ('Total', 'Total'), ('Begin-Total', 'Begin-Total'), ('End-Total', 'End-Total')], max_length=255, null=True, verbose_name='Account Type')),
                ('totaling', models.CharField(blank=True, max_length=255, null=True, verbose_name='Totaling')),
                ('direct_posting', models.BooleanField(default=False, verbose_name='Direct Posting')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked')),
            ],
            options={
                'verbose_name': 'General Ledger Account',
                'verbose_name_plural': 'General Ledger Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('document_type', models.CharField(blank=True, choices=[('default', ''), ('Invoice', 'Invoice'), ('Payment', 'Payment')], default='default', max_length=255, null=True, verbose_name='Document Type')),
                ('posting_date', models.DateField(verbose_name='Posting Date')),
                ('document_no', models.CharField(max_length=255, verbose_name='Document No.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('balance_account_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bal Account No.')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('receipt_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Receipt No.')),
                ('balancing_account_type', models.CharField(blank=True, choices=financials.enums.BalacingAccountType.choices, max_length=255, null=True, verbose_name='Bal. Account Type')),
                ('general_posting_type', models.CharField(blank=True, choices=financials.enums.GeneralPostingType.choices, default='default', max_length=255, null=True, verbose_name='General Posting Type')),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction No.')),
                ('reversed_by_transaction_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reversed By')),
                ('reversed', models.BooleanField(db_index=True, default=False, help_text='Indicates if this entry has been reversed', verbose_name='Reversed')),
                ('reversed_by_document_no', models.CharField(blank=True, help_text='Credit memo or reversing document number', max_length=50, null=True, verbose_name='Reversed By Document No.')),
                ('reversed_date', models.DateField(blank=True, help_text='Date when this entry was reversed', null=True, verbose_name='Reversal Date')),
                ('reverses_entry_no', models.IntegerField(blank=True, db_index=True, help_text='If this is a reversing entry, the ID of the entry it reverses', null=True, verbose_name='Reverses Entry No.')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('document_type', models.CharField(choices=[('default', ''), ('Invoice', 'Invoice'), ('Payment', 'Payment')], default='default', max_length=255, verbose_name='Document Type')),
                ('document_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document No.')),
                ('external_document_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='External Document No.')),
                ('account_type', models.CharField(choices=financials.enums.BalacingAccountType.choices, default='G/L Account', max_length=255, verbose_name='Account Type')),
                ('message_to_recipient', models.TextField(blank=True, null=True, verbose_name='Message to Recipient')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('bal_account_type', models.CharField(choices=financials.enums.BalacingAccountType.choices, default='G/L Account', max_length=255, verbose_name='Bal. Account Type')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('status', models.CharField(choices=[('default', ''), ('Open', 'Open'), ('Posted', 'Posted')], default='Open', max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('bal_account_type', models.CharField(choices=financials.enums.BalacingAccountType.choices, default='G/L Account', max_length=255, verbose_name='Bal. Account Type')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('bal_account_type', models.CharField(choices=financials.enums.BalacingAccountType.choices, default='G/L Account', max_length=20, verbose_name='Bal. Account Type')),
                ('requires_amount_received', models.BooleanField(default=True, help_text='Whether this payment method requires an amount received field in sales interface', verbose_name='Requires Amount Received')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['code'],
            },
        ),
    ]
