# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        ('financials', '0001_initial'),
        ('postings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='g_laccount',
            name='general_product_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='postings.generalproductpostinggroup'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger_entries', to='dimension.dimensionvalue'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='dimension_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimension_2_entries', to='dimension.dimension'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='general_business_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_business_posting_group_entries', to='postings.generalbusinesspostinggroup'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='general_product_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_product_posting_group_entries', to='postings.generalproductpostinggroup'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_entries', to='financials.g_laccount'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='reversed_by_user',
            field=models.ForeignKey(blank=True, help_text='User who performed the reversal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_entry_reversals', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By User'),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledgerentry',
            name='vat_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vat_account_entries', to='financials.g_laccount'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_dimension_1_entries', to='dimension.dimension'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='global_dimension_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_dimension_2_entries', to='dimension.dimension'),
        ),
    ]
