# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0002_initial'),
        ('financials', '0002_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_entries_customer', to='sales.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_entries_gl', to='financials.g_laccount', verbose_name='G/L Account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gl_balancing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_entries_gl_balancing', to='financials.g_laccount', verbose_name='G/L Balancing Account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_entries_vendor', to='purchases.vendor', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='bal_account_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='financials.g_laccount', verbose_name='Bal. Account No.'),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='no_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='setup.noseries', verbose_name='No. Series'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.paymentbatch'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bal_account_no',
            field=models.ForeignKey(blank=True, help_text="G/L Account when Bal. Account Type is 'G/L Account'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods_gl', to='financials.g_laccount', verbose_name='G/L Account No.'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bal_bank_account_no',
            field=models.ForeignKey(blank=True, help_text="Bank Account when Bal. Account Type is 'Bank Account'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods_bank', to='bank_account.bankaccount', verbose_name='Bank Account No.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['created_at'], name='financials__created_0cbdc3_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['system_id'], name='financials__system__718421_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgersetup',
            index=models.Index(fields=['created_at'], name='financials__created_853cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgersetup',
            index=models.Index(fields=['system_id'], name='financials__system__bbf151_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['created_at'], name='financials__created_a0ac18_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['system_id'], name='financials__system__a94d5f_idx'),
        ),
    ]
