# Generated by Django 5.1.7 on 2026-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgersetup',
            name='enable_sales_line_type_selection',
            field=models.BooleanField(default=False, help_text='When enabled, sales and order lines show Type (Item/Resource) as the first field and allow resource lines.', verbose_name='Enable Sales Line Type Selection'),
        ),
    ]
