# Generated by Django 5.1.7 on 2026-02-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0003_dimension_id_pk'),
        ('financials', '0004_add_enable_sales_line_type_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgerentry',
            name='dimension_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger_entries_dimension_2', to='dimension.dimensionvalue'),
        ),
    ]
