# Generated by Django 5.1.7 on 2026-02-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_add_shortcut_dimensions_to_general_ledger_setup'),
        ('financials', '0006_dimension_set_on_gl_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgersetup',
            name='shortcut_dimension_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcut_dimension_3_setups', to='dimension.dimension', verbose_name='Shortcut Dimension 3'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='shortcut_dimension_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcut_dimension_4_setups', to='dimension.dimension', verbose_name='Shortcut Dimension 4'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='shortcut_dimension_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcut_dimension_5_setups', to='dimension.dimension', verbose_name='Shortcut Dimension 5'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='shortcut_dimension_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcut_dimension_6_setups', to='dimension.dimension', verbose_name='Shortcut Dimension 6'),
        ),
    ]
