# Generated by Django 5.1.7 on 2026-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_add_shortcut_dimensions_to_general_ledger_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgersetup',
            name='enable_multiple_branches',
            field=models.BooleanField(default=False, help_text='When enabled, users must be assigned a branch and data is filtered by branch. Requires Global Dimension 1 to be configured (e.g. BRANCH).', verbose_name='Enable Multiple Branches'),
        ),
    ]
