# Generated by Django 5.1.7 on 2026-03-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_add_enable_multiple_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgersetup',
            name='default_vat_date',
            field=models.CharField(blank=True, choices=[('posting_date', 'Posting Date'), ('document_date', 'Document Date')], default='posting_date', help_text='Default source for VAT date on documents.', max_length=20, null=True, verbose_name='Default VAT Date'),
        ),
        migrations.AddField(
            model_name='generalledgersetup',
            name='vat_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, VAT is calculated and posted on sales and purchase documents. Requires VAT Posting Setup, and VAT posting groups on customers, vendors, and items.', verbose_name='Enable VAT'),
        ),
    ]
