# Generated by Django 5.1.7 on 2026-03-05 21:09

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


def create_vat_entry_table_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = 'financials_vatentry'
            """
        )
        if cursor.fetchone():
            return
    from financials.models import VatEntry

    schema_editor.create_model(VatEntry)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0006_add_shortcut_dimensions_to_general_ledger_setup"),
        ("financials", "0009_add_vat_enabled_to_general_ledger_setup"),
        ("postings", "0003_add_vat_posting_setup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="VatEntry",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "posting_date",
                            models.DateField(verbose_name="Posting Date"),
                        ),
                        (
                            "document_type",
                            models.CharField(max_length=255, verbose_name="Document Type"),
                        ),
                        (
                            "document_no",
                            models.CharField(max_length=255, verbose_name="Document No."),
                        ),
                        (
                            "type",
                            models.CharField(
                                choices=[("Sale", "Sale"), ("Purchase", "Purchase")],
                                max_length=20,
                                verbose_name="Type",
                            ),
                        ),
                        (
                            "base",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                help_text="Taxable base amount (excl. VAT)",
                                max_digits=18,
                                verbose_name="Base",
                            ),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                help_text="VAT amount",
                                max_digits=18,
                                verbose_name="Amount",
                            ),
                        ),
                        (
                            "vat_percent",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                max_digits=5,
                                verbose_name="VAT %",
                            ),
                        ),
                        (
                            "vat_calculation_type",
                            models.CharField(
                                default="Normal",
                                max_length=20,
                                verbose_name="VAT Calculation Type",
                            ),
                        ),
                        (
                            "transaction_no",
                            models.CharField(
                                blank=True,
                                max_length=255,
                                null=True,
                                verbose_name="Transaction No.",
                            ),
                        ),
                        (
                            "general_business_posting_group",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="vat_entries",
                                to="postings.generalbusinesspostinggroup",
                            ),
                        ),
                        (
                            "general_product_posting_group",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="vat_entries_prod",
                                to="postings.generalproductpostinggroup",
                            ),
                        ),
                        (
                            "global_dimension_1",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="vat_entries",
                                to="dimension.dimensionvalue",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="vat_entries",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "vat_account",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="vat_entries",
                                to="financials.g_laccount",
                                verbose_name="VAT Account",
                            ),
                        ),
                        (
                            "vat_business_posting_group",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="vat_entries",
                                to="postings.vatbusinesspostinggroup",
                                verbose_name="VAT Bus. Posting Group",
                            ),
                        ),
                        (
                            "vat_product_posting_group",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="vat_entries",
                                to="postings.vatproductpostinggroup",
                                verbose_name="VAT Prod. Posting Group",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "VAT Entry",
                        "verbose_name_plural": "VAT Entries",
                        "ordering": ["-posting_date", "-created_at"],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    create_vat_entry_table_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
