# Generated by Django 5.1.7 on 2026-07-11 07:38

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_general_journal_line_applies'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportColumnGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Financial Report Column Group',
                'verbose_name_plural': 'Financial Report Column Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReportRowGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Financial Report Row Group',
                'verbose_name_plural': 'Financial Report Row Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Description')),
                ('period_type', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Year', 'Year'), ('Accounting Period', 'Accounting Period')], default='Month', max_length=30, verbose_name='Period Type')),
                ('show_all_lines', models.BooleanField(default=False, verbose_name='Show All Lines')),
                ('use_amounts_in_add_currency', models.BooleanField(default=False, verbose_name='Use Amounts in Add. Reporting Currency')),
                ('dimension_1_filter', models.CharField(blank=True, default='', max_length=250, verbose_name='Dimension 1 Filter')),
                ('dimension_2_filter', models.CharField(blank=True, default='', max_length=250, verbose_name='Dimension 2 Filter')),
                ('dimension_3_filter', models.CharField(blank=True, default='', max_length=250, verbose_name='Dimension 3 Filter')),
                ('dimension_4_filter', models.CharField(blank=True, default='', max_length=250, verbose_name='Dimension 4 Filter')),
                ('column_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_reports', to='financials.financialreportcolumngroup', to_field='name', verbose_name='Financial Report Column Group')),
                ('row_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_reports', to='financials.financialreportrowgroup', to_field='name', verbose_name='Financial Report Row Group')),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReportColumnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('line_no', models.IntegerField(verbose_name='Line No.')),
                ('column_header', models.CharField(blank=True, default='', max_length=250, verbose_name='Column Header')),
                ('column_type', models.CharField(choices=[('Net Change', 'Net Change'), ('Balance at Date', 'Balance at Date'), ('Beginning Balance', 'Beginning Balance')], default='Net Change', max_length=50, verbose_name='Column Type')),
                ('column_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financials.financialreportcolumngroup', verbose_name='Column Group')),
            ],
            options={
                'verbose_name': 'Financial Report Column Line',
                'verbose_name_plural': 'Financial Report Column Lines',
                'ordering': ['line_no'],
                'unique_together': {('column_group', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReportRowLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('line_no', models.IntegerField(verbose_name='Line No.')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Description')),
                ('row_type', models.CharField(choices=[('Header', 'Header'), ('Posting', 'Posting'), ('Total', 'Total'), ('Begin-Total', 'Begin-Total'), ('End-Total', 'End-Total')], default='Posting', max_length=50, verbose_name='Row Type')),
                ('totaling', models.CharField(blank=True, max_length=250, null=True, verbose_name='Totaling')),
                ('show_opposite_sign', models.BooleanField(default=False, verbose_name='Show Opposite Sign')),
                ('row_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financials.financialreportrowgroup', verbose_name='Row Group')),
            ],
            options={
                'verbose_name': 'Financial Report Row Line',
                'verbose_name_plural': 'Financial Report Row Lines',
                'ordering': ['line_no'],
                'unique_together': {('row_group', 'line_no')},
            },
        ),
    ]
