# Generated by Django 5.1.7 on 2026-07-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_financial_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='column_definition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='financial_reports',
                to='financials.financialreportcolumngroup',
                to_field='name',
                verbose_name='Financial Report Column Group',
            ),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='row_definition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='financial_reports',
                to='financials.financialreportrowgroup',
                to_field='name',
                verbose_name='Financial Report Row Group',
            ),
        ),
    ]
