# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='general_product_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.generalproductpostinggroup', verbose_name='General Product Posting Group'),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.inventorypostinggroup', verbose_name='Inventory Posting Group'),
        ),
    ]
