# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        ('items', '0002_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='production_bom',
            field=models.OneToOneField(blank=True, help_text='Production BOM for this item (Service or Non-Inventory items only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='production.productionbom', verbose_name='Production BOM'),
        ),
        migrations.AddField(
            model_name='itemattributeentry',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_entries', to='items.itemattribute'),
        ),
        migrations.AddField(
            model_name='itemattributeentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_entries', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemattributeentry',
            name='selected_values',
            field=models.ManyToManyField(blank=True, related_name='attribute_entries', to='items.itemattributevalue'),
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='items.itemattributevalue'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='items.itemattribute'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.itemcategory', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemcategory', verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_ledger_entries', to='dimension.dimensionvalue'),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='reversed_by_user',
            field=models.ForeignKey(blank=True, help_text='User who performed the reversal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_ledger_reversals', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By User'),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='tracking_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_tracking_code', to='items.itemtrackingcodes'),
        ),
        migrations.AddField(
            model_name='itemunitofmeasure',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='unit_of_measure_code',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemunitofmeasure', verbose_name='Unit of Measure Code'),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='item_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_journals', to='items.itemunitofmeasure', verbose_name='Item Unit of Measure'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_unit_of_measure', to='items.itemunitofmeasure', verbose_name='Purchase Unit of Measure'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_unit_of_measure', to='items.itemunitofmeasure', verbose_name='Sales Unit of Measure'),
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location'),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_specifications', to='items.item'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='item_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_journal_tracking_specifications', to='items.itemjournal', verbose_name='Item Journal'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location'),
        ),
    ]
