# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingspecification',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoice', verbose_name='Purchase Invoice'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='purchase_invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoiceline', verbose_name='Purchase Invoice Line'),
        ),
    ]
