# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        ('items', '0004_initial'),
        ('postings', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingspecification',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoice', verbose_name='Sales Invoice'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='sales_invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoiceline', verbose_name='Sales Invoice Line'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='item_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journal_tracking_specifications', to='items.trackingspecification'),
        ),
        migrations.AddField(
            model_name='itemunitofmeasure',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='value_entries', to='dimension.dimensionvalue'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='general_business_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.generalbusinesspostinggroup', verbose_name='General Business Posting Group'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='general_product_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.generalproductpostinggroup', verbose_name='General Product Posting Group'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='inventory_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postings.inventorypostinggroup', verbose_name='Inventory Posting Group'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='item_ledger_entry_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemledgerentries', verbose_name='Item Ledger Entry No'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='location_code',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='reversed_by_user',
            field=models.ForeignKey(blank=True, help_text='User who performed the reversal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='value_entry_reversals', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By User'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='vat_business_posting_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.vatbusinesspostinggroup', verbose_name='VAT Business Posting Group'),
        ),
        migrations.AddField(
            model_name='valueentry',
            name='vat_posting_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.vatproductpostinggroup', verbose_name='VAT Posting Group'),
        ),
        migrations.AlterUniqueTogether(
            name='itemattributeentry',
            unique_together={('item', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('description', 'parent')},
        ),
        migrations.AddConstraint(
            model_name='trackingspecification',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_no__isnull', False), models.Q(('serial_no', ''), _negated=True)), fields=('serial_no',), name='unique_non_empty_serial_no'),
        ),
        migrations.AddConstraint(
            model_name='itemunitofmeasure',
            constraint=models.UniqueConstraint(fields=('item', 'unit_of_measure'), name='unique_item_unit_of_measure'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'Inventory')), fields=('item_name', 'no'), name='unique_item_name'),
        ),
        migrations.AddIndex(
            model_name='valueentry',
            index=models.Index(fields=['created_at'], name='items_value_created_8a93ed_idx'),
        ),
        migrations.AddIndex(
            model_name='valueentry',
            index=models.Index(fields=['system_id'], name='items_value_system__838d7f_idx'),
        ),
    ]
