# Generated by Django 5.1.7 on 2025-12-21 03:00

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_item_journal_template(apps, schema_editor):
    """
    Create default Item Journal Template with name "ITEM", description "Item Journal",
    type "item", and no_series from InventorySetup.item_journal_no_series.
    """
    ItemJournalTemplate = apps.get_model('items', 'ItemJournalTemplate')
    InventorySetup = apps.get_model('setup', 'InventorySetup')
    
    # Get the InventorySetup (should be only one per tenant)
    inventory_setup = InventorySetup.objects.first()
    
    # Get the item journal no series from InventorySetup
    no_series = None
    if inventory_setup and inventory_setup.item_journal_no_series:
        no_series = inventory_setup.item_journal_no_series
    
    # Create the default template
    ItemJournalTemplate.objects.get_or_create(
        name='ITEM',
        defaults={
            'description': 'Item Journal',
            'type': 'item',
            'no_series': no_series,
        }
    )


def reverse_create_default_item_journal_template(apps, schema_editor):
    """
    Reverse migration: delete the default template.
    """
    ItemJournalTemplate = apps.get_model('items', 'ItemJournalTemplate')
    ItemJournalTemplate.objects.filter(name='ITEM').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_initial'),
        ('setup', '0002_add_item_journal_template_and_inventory_setup_item_journal_no_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemJournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(help_text='Template name (e.g., ITEM)', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.CharField(help_text='Template description', max_length=200, verbose_name='Description')),
                ('type', models.CharField(choices=[('item', 'Item'), ('transfer', 'Transfer'), ('phys_inventory', 'Phys. Inventory'), ('output', 'Output'), ('production_order', 'Production Order')], help_text='Journal template type', max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Item Journal Template',
                'verbose_name_plural': 'Item Journal Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemjournal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='itemjournal',
            index=models.Index(fields=['created_at'], name='items_itemj_created_e51c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemjournal',
            index=models.Index(fields=['system_id'], name='items_itemj_system__6c21d9_idx'),
        ),
        migrations.AlterModelTable(
            name='itemjournal',
            table=None,
        ),
        migrations.AddField(
            model_name='itemjournaltemplate',
            name='no_series',
            field=models.ForeignKey(blank=True, help_text='Number series for journal entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journal_templates', to='setup.noseries', verbose_name='No. Series'),
        ),
        migrations.RunPython(
            create_default_item_journal_template,
            reverse_create_default_item_journal_template,
        ),
    ]
