# Generated by Django 5.1.7 on 2025-12-21 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_add_item_journal_template_and_inventory_setup_item_journal_no_series'),
        ('setup', '0002_add_item_journal_template_and_inventory_setup_item_journal_no_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemjournal',
            name='journal_template',
            field=models.ForeignKey(blank=True, help_text='Item journal template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journals', to='items.itemjournaltemplate', verbose_name='Journal Template'),
        ),
        migrations.AddIndex(
            model_name='itemjournaltemplate',
            index=models.Index(fields=['name'], name='items_itemj_name_999473_idx'),
        ),
        migrations.AddIndex(
            model_name='itemjournaltemplate',
            index=models.Index(fields=['type'], name='items_itemj_type_763f3d_idx'),
        ),
    ]
