# Generated by Django 5.1.7 on 2025-12-21 07:49

from django.db import migrations, models


def create_prod_orde_template(apps, schema_editor):
    """
    Create "PROD. ORDE" Item Journal Template for production orders.
    Links to PRODORDE no series if it exists.
    """
    ItemJournalTemplate = apps.get_model('items', 'ItemJournalTemplate')
    NoSeries = apps.get_model('setup', 'NoSeries')
    
    # Try to get PRODORDE no series
    no_series = None
    try:
        no_series = NoSeries.objects.get(code='PRODORDE')
    except NoSeries.DoesNotExist:
        pass  # Keep it None if no series doesn't exist yet
    
    # Create the template
    ItemJournalTemplate.objects.get_or_create(
        name='PROD. ORDE',
        defaults={
            'description': 'Production Order Item Journal',
            'type': 'production_order',
            'no_series': no_series,
        }
    )


def reverse_create_prod_orde_template(apps, schema_editor):
    """
    Reverse migration: delete the PROD. ORDE template.
    """
    ItemJournalTemplate = apps.get_model('items', 'ItemJournalTemplate')
    ItemJournalTemplate.objects.filter(name='PROD. ORDE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_add_journal_template_to_item_journal'),
        ('setup', '0002_add_item_journal_template_and_inventory_setup_item_journal_no_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemjournal',
            name='entry_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('PositiveAdjustment', 'Positive Adjustment'), ('NegativeAdjustment', 'Negative Adjustment'), ('DirectCost', 'Direct Cost'), ('Consumption', 'Consumption'), ('Output', 'Output')], max_length=255),
        ),
        migrations.AlterField(
            model_name='itemledgerentries',
            name='entry_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('PositiveAdjustment', 'Positive Adjustment'), ('NegativeAdjustment', 'Negative Adjustment'), ('DirectCost', 'Direct Cost'), ('Consumption', 'Consumption'), ('Output', 'Output')], editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='valueentry',
            name='entry_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('PositiveAdjustment', 'Positive Adjustment'), ('NegativeAdjustment', 'Negative Adjustment'), ('DirectCost', 'Direct Cost'), ('Consumption', 'Consumption'), ('Output', 'Output')], editable=False, max_length=255),
        ),
        migrations.RunPython(
            create_prod_orde_template,
            reverse_create_prod_orde_template,
        ),
    ]
