# Generated by Django 5.1.7 on 2025-12-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_create_prod_orde_template'),
        ('production', '0003_add_production_order_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemjournal',
            name='production_order',
            field=models.ForeignKey(blank=True, help_text='Production order this journal entry is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journals', to='production.productionorder', verbose_name='Production Order'),
        ),
    ]
