# Generated by Django 5.1.7 on 2025-12-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_add_production_order_to_item_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemjournal',
            name='type',
            field=models.CharField(blank=True, choices=[('work_center', 'Work Center'), ('machine_center', 'Machine Center'), ('resource', 'Resource')], help_text='Type of capacity used (Work Center, Machine Center, or Resource). Filled when entry_type is Output.', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
