# Generated by Django 5.1.7 on 2025-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_add_type_to_item_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flushing_method',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Forward', 'Forward'), ('Backward', 'Backward'), ('Pick + Forward', 'Pick + Forward'), ('Pick + Backward', 'Pick + Backward')], help_text='Flushing method for production orders', max_length=20, null=True, verbose_name='Flushing Method'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturing_policy',
            field=models.CharField(blank=True, choices=[('Make-to-Stock', 'Make-to-Stock'), ('Make-to-Order', 'Make-to-Order')], help_text='Manufacturing policy: Make-to-Stock or Make-to-Order', max_length=20, null=True, verbose_name='Manufacturing Policy'),
        ),
        migrations.AddField(
            model_name='item',
            name='replenishment_system',
            field=models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Prod. Order', 'Prod. Order'), ('Transfer', 'Transfer'), ('Assembly', 'Assembly')], help_text='Replenishment system for this item', max_length=20, null=True, verbose_name='Replenishment System'),
        ),
    ]
