# Generated by Django 5.1.7 on 2026-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_flushing_method_item_manufacturing_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemunitofmeasure',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this unit of measure. If blank, calculated from item.unit_price * quantity_per_unit', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
