# Generated by Django 5.1.7 on 2026-01-06 02:15

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_itemunitofmeasure_price'),
        ('setup', '0005_alter_journalsetup_journal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemjournal',
            name='calculated_quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='System-calculated quantity from ItemLedgerEntries', null=True, verbose_name='Calculated Quantity'),
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='physical_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Physically counted quantity', null=True, verbose_name='Physical Quantity'),
        ),
        migrations.CreateModel(
            name='ItemJournalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(help_text='Batch name (e.g., DEFAULT)', max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Batch description', max_length=200, verbose_name='Description')),
                ('journal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='items.itemjournaltemplate', verbose_name='Journal Template')),
                ('no_series', models.ForeignKey(blank=True, help_text='Number series for posting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journal_batches', to='setup.noseries', verbose_name='No. Series')),
            ],
            options={
                'verbose_name': 'Item Journal Batch',
                'verbose_name_plural': 'Item Journal Batches',
                'ordering': ['journal_template', 'name'],
                'unique_together': {('journal_template', 'name')},
            },
        ),
        migrations.AddField(
            model_name='itemjournal',
            name='journal_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_journals', to='items.itemjournalbatch', verbose_name='Journal Batch'),
        ),
    ]
