# Generated by Django 5.1.7 on 2026-02-20 20:31

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_itemjournal_calculated_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysInventoryLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('entry_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Entry No.')),
                ('document_no', models.CharField(help_text='Journal document number', max_length=20, verbose_name='Document No.')),
                ('posting_date', models.DateField(help_text='Date when the physical inventory was posted', verbose_name='Posting Date')),
                ('item_no', models.CharField(help_text='Item number (denormalized for reporting)', max_length=20, verbose_name='Item No.')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('qty_expected', models.DecimalField(decimal_places=5, help_text='System quantity before physical count (calculated quantity)', max_digits=18, verbose_name='Qty. (Expected)')),
                ('qty_phys_inventory', models.DecimalField(decimal_places=5, help_text='Actual counted quantity (physical quantity)', max_digits=18, verbose_name='Qty. (Phys. Inventory)')),
                ('quantity', models.DecimalField(decimal_places=5, help_text='Variance (Phys. Inventory - Expected)', max_digits=18, verbose_name='Quantity')),
                ('entry_type', models.CharField(help_text='Positive or Negative Adjustment', max_length=50, verbose_name='Entry Type')),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost used for this count', max_digits=18, null=True, verbose_name='Unit Amount')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Unit Cost')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phys_inventory_ledger_entries', to='items.item', verbose_name='Item')),
                ('item_ledger_entry', models.ForeignKey(blank=True, help_text='Link to the item ledger entry created by this count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phys_inventory_ledger_entries', to='items.itemledgerentries', verbose_name='Item Ledger Entry No.')),
                ('journal_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phys_inventory_ledger_entries', to='items.itemjournalbatch', verbose_name='Journal Batch')),
                ('location_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phys_inventory_ledger_entries', to='items.location', verbose_name='Location Code')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phys_inventory_ledger_entries', to='items.itemunitofmeasure', verbose_name='Unit of Measure')),
                ('user', models.ForeignKey(help_text='User who posted the physical inventory', on_delete=django.db.models.deletion.PROTECT, related_name='phys_inventory_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Phys. Inventory Ledger Entry',
                'verbose_name_plural': 'Phys. Inventory Ledger Entries',
                'db_table': 'items_physinventoryledgerentry',
                'ordering': ['-posting_date', '-entry_no'],
                'indexes': [models.Index(fields=['item', 'posting_date'], name='items_physi_item_id_f2330d_idx'), models.Index(fields=['location_code', 'posting_date'], name='items_physi_locatio_59209c_idx'), models.Index(fields=['document_no'], name='items_physi_documen_51546d_idx')],
            },
        ),
    ]
