# Generated by Django 5.1.7 on 2026-02-22 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_physinventoryledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingspecification',
            name='source_batch_name',
            field=models.CharField(blank=True, help_text="e.g. 'PHYS. INV. - Physical Inventory' or 'ITEM - DEFAULT'", max_length=100, verbose_name='Source Batch Name'),
        ),
        migrations.AddField(
            model_name='trackingspecification',
            name='source_id',
            field=models.ForeignKey(blank=True, help_text='Journal batch this spec belongs to (Item Journal vs Phys. Inventory)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_specifications', to='items.itemjournalbatch', verbose_name='Source ID'),
        ),
    ]
