# Generated by Django 5.1.7 on 2026-02-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_add_tracking_spec_source_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemjournalbatch",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Use as default batch when creating new journal entries for this template",
                verbose_name="Default",
            ),
        ),
    ]
