# Generated by Django 5.1.7 on 2026-02-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_backfill_tracking_spec_source_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemjournalbatch',
            name='default',
        ),
        migrations.AlterField(
            model_name='trackingspecification',
            name='source_batch_name',
            field=models.CharField(blank=True, default='', help_text="Default: from item journal batch (e.g. 'PHYS. INV. - Physical Inventory' or 'ITEM - DEFAULT')", max_length=100, verbose_name='Source Batch Name'),
        ),
    ]
