# Generated by Django 5.1.7 on 2026-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_tracking_spec_source_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueentry',
            name='cost_amount_non_invtbl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cost for Service and Non-Inventory items (not reconciled to G/L)', max_digits=18, null=True, verbose_name='Cost Amount (Non-Invtbl.)'),
        ),
    ]
