# Generated by Django 5.1.7 on 2026-03-25 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_add_vat_posting_groups_to_master_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manual_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual unit cost for Service and Non-Inventory items', max_digits=15, null=True, verbose_name='Manual Unit Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Unit Price'),
        ),
    ]
