# Generated by Django 5.1.7 on 2026-04-20 12:53

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_item_manual_unit_cost_alter_item_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Auto-generated (e.g. XL-RED) or entered manually.', max_length=50, verbose_name='Variant Code')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('unit_price', models.PositiveIntegerField(blank=True, help_text="Leave blank to inherit the item's base price.", null=True, verbose_name='Unit Price')),
                ('bar_code_no', models.CharField(blank=True, max_length=100, verbose_name='Barcode')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item Variant',
                'verbose_name_plural': 'Item Variants',
                'db_table': 'items_variant',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='itemledgerentries',
            name='variant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='items.itemvariant', verbose_name='Variant'),
        ),
        migrations.CreateModel(
            name='ItemVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=50, verbose_name='Option Name')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='items.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item Variant Option',
                'verbose_name_plural': 'Item Variant Options',
                'db_table': 'items_variantoption',
                'ordering': ['display_order', 'name'],
                'unique_together': {('item', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemVariantOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='items.itemvariantoption', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Item Variant Option Value',
                'verbose_name_plural': 'Item Variant Option Values',
                'db_table': 'items_variantoptionvalue',
                'ordering': ['display_order', 'value'],
                'unique_together': {('option', 'value')},
            },
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='items.itemvariantoptionvalue', verbose_name='Option Values'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('item', 'code')},
        ),
    ]
