# Generated by Django 5.1.7 on 2026-04-21 15:56
#
# Database: add nullable bigint only (no DB-level FK). Some tenant schemas have
# dimension_dimensionvalue without a standard id PK, which breaks AddField FK creation.
# ORM still treats this as ForeignKey; integrity matches other item ledger dimension fields.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0006_add_shortcut_dimensions_to_general_ledger_setup"),
        ("items", "0026_add_item_variants"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "Item Ledger Entries"
                    ADD COLUMN IF NOT EXISTS global_dimension_2_id bigint NULL;
                    ALTER TABLE items_valueentry
                    ADD COLUMN IF NOT EXISTS global_dimension_2_id bigint NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE "Item Ledger Entries"
                    DROP COLUMN IF EXISTS global_dimension_2_id;
                    ALTER TABLE items_valueentry
                    DROP COLUMN IF EXISTS global_dimension_2_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="itemledgerentries",
                    name="global_dimension_2",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="item_ledger_entries_global_dim_2",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 2",
                    ),
                ),
                migrations.AddField(
                    model_name="valueentry",
                    name="global_dimension_2",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="value_entries_global_dim_2",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 2",
                    ),
                ),
            ],
        ),
    ]
