[program:zentrov2-flower]
directory=/root/projects/zentro-appv2/backend
command=/root/projects/zentro-appv2/env/bin/celery -A core flower --basic_auth=CHANGE_USER:CHANGE_PASSWORD --port=5557 --address=127.0.0.1
autostart=true
autorestart=true
stderr_logfile=/root/projects/zentro-appv2/logs/flower.err.log
stdout_logfile=/root/projects/zentro-appv2/logs/flower.out.log
user=root
group=root
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8,DJANGO_SETTINGS_MODULE=core.settingsprod
