[program:zentrov2-celery]
directory=/root/projects/zentro-appv2/backend
command=/root/projects/zentro-appv2/env/bin/celery -A core worker --pool=solo -l info
autostart=true
autorestart=true
stderr_logfile=/root/projects/zentro-appv2/logs/celery.err.log
stdout_logfile=/root/projects/zentro-appv2/logs/celery.out.log
user=root
group=root
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8,DJANGO_SETTINGS_MODULE=core.settingsprod
