[program:zentrov2-celery-beat]
directory=/root/projects/zentro-appv2/backend
command=/root/projects/zentro-appv2/env/bin/celery -A core beat -l info
autostart=true
autorestart=true
stderr_logfile=/root/projects/zentro-appv2/logs/celery-beat.err.log
stdout_logfile=/root/projects/zentro-appv2/logs/celery-beat.out.log
user=root
group=root
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8,DJANGO_SETTINGS_MODULE=core.settingsprod
