# Generated by Django 5.1.7 on 2026-03-26 16:04

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('search_mode', models.CharField(choices=[('barcode', 'Barcode'), ('realtime', 'Realtime')], default='barcode', max_length=20)),
                ('barcode_scanner_enabled', models.BooleanField(default=True)),
                ('barcode_beep_enabled', models.BooleanField(default=True)),
                ('printer_type', models.CharField(choices=[('sunmi', 'Sunmi'), ('bluetooth', 'Bluetooth'), ('none', 'None')], default='none', max_length=20)),
                ('printer_device_name', models.CharField(blank=True, default='', max_length=255)),
                ('printer_mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('printer_paper_width', models.CharField(choices=[('58', '58'), ('80', '80')], default='58', max_length=2)),
                ('printer_copies', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile App User Settings',
                'verbose_name_plural': 'Mobile App User Settings',
                'db_table': 'settings_mobileappusersettings',
            },
        ),
    ]
