# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_host_user', models.EmailField(max_length=254, unique=True)),
                ('email_host_password', models.CharField(max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=255)),
                ('email_category', models.CharField(choices=[('verification', 'verification'), ('password_reset', 'password_reset'), ('invitation', 'invitation'), ('other', 'other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'No Series',
                'verbose_name_plural': 'No Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('journal_type', models.CharField(choices=[('item', 'item'), ('payment', 'payment'), ('expense', 'expense')], default='item', max_length=255)),
                ('journal_no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.noseries', verbose_name="Journal No's.")),
            ],
            options={
                'verbose_name': 'Journal Setup',
                'verbose_name_plural': 'Journal Setup',
            },
        ),
        migrations.CreateModel(
            name='InventorySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('item_no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.noseries', verbose_name="Item No's.")),
            ],
            options={
                'verbose_name_plural': 'Inventory Setup',
            },
        ),
        migrations.CreateModel(
            name='BankAccountSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('bank_account_no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.noseries', verbose_name="Bank Account No's.")),
            ],
            options={
                'verbose_name': 'Bank Account Setup',
                'verbose_name_plural': 'Bank Account Setup',
            },
        ),
        migrations.CreateModel(
            name='ProductionSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('bom_no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_production_setups', to='setup.noseries', verbose_name="BOM No's.")),
                ('production_order_no_series', models.ForeignKey(blank=True, help_text='Number series for Production Orders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_production_setups', to='setup.noseries', verbose_name="Production Order No's.")),
            ],
            options={
                'verbose_name': 'Production Setup',
                'verbose_name_plural': 'Production Setup',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='setup_sites_created_316a16_idx'), models.Index(fields=['system_id'], name='setup_sites_system__d9581f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(choices=[('items', 'items'), ('sales', 'sales'), ('purchases', 'purchases'), ('inventory', 'inventory')], max_length=255)),
                ('file', models.FileField(upload_to='upload_templates/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='setup_uploa_created_c103be_idx'), models.Index(fields=['system_id'], name='setup_uploa_system__a4b6ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoSeriesLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('start_number', models.CharField(max_length=20)),
                ('end_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_used_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('increment_by', models.IntegerField(default=1)),
                ('no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.noseries')),
            ],
            options={
                'verbose_name': 'No Series Line',
                'verbose_name_plural': 'No Series Lines',
                'ordering': ['-created_at'],
                'unique_together': {('no_series', 'start_number')},
            },
        ),
    ]
