# Generated by Django 5.1.7 on 2025-12-21 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysetup',
            name='item_journal_no_series',
            field=models.ForeignKey(blank=True, help_text='Number series for item journals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_setups_item_journal', to='setup.noseries', verbose_name="Item Journal No's."),
        ),
    ]
