# Generated by Django 5.1.7 on 2025-12-23 05:47

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_add_item_journal_template_and_inventory_setup_item_journal_no_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('bom_no_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_manufacturing_setups', to='setup.noseries', verbose_name="BOM No's.")),
                ('machine_center_no_series', models.ForeignKey(blank=True, help_text='Number series for Machine Centers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_center_manufacturing_setups', to='setup.noseries', verbose_name="Machine Center No's.")),
                ('production_order_no_series', models.ForeignKey(blank=True, help_text='Number series for Production Orders', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_manufacturing_setups', to='setup.noseries', verbose_name="Production Order No's.")),
                ('routing_no_series', models.ForeignKey(blank=True, help_text='Number series for Routings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_manufacturing_setups', to='setup.noseries', verbose_name="Routing No's.")),
                ('work_center_no_series', models.ForeignKey(blank=True, help_text='Number series for Work Centers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_center_manufacturing_setups', to='setup.noseries', verbose_name="Work Center No's.")),
            ],
            options={
                'verbose_name': 'Manufacturing Setup',
                'verbose_name_plural': 'Manufacturing Setup',
            },
        ),
        migrations.DeleteModel(
            name='ProductionSetup',
        ),
    ]
