# Generated by Django 5.1.7 on 2025-12-23 06:02

import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_manufacturingsetup_delete_productionsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(default='Seed Manager', help_text='Name for the seed manager instance', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of seed operations')),
            ],
            options={
                'verbose_name': 'Seed Manager',
                'verbose_name_plural': 'Seed Manager',
                'ordering': ['-created_at'],
            },
        ),
    ]
