# Generated by Django 5.1.7 on 2026-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_seedmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsetup',
            name='journal_type',
            field=models.CharField(choices=[('item', 'item'), ('payment', 'payment'), ('expense', 'expense'), ('loan', 'loan')], default='item', max_length=255),
        ),
    ]
