# Generated by Django 5.1.7 on 2026-01-28 13:56

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_journalsetup_journal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('resource_no_series', models.ForeignKey(help_text='Number series for Resources', on_delete=django.db.models.deletion.CASCADE, to='setup.noseries', verbose_name="Resource No's.")),
            ],
            options={
                'verbose_name': 'Resource Setup',
                'verbose_name_plural': 'Resource Setup',
            },
        ),
    ]
