# Generated by Django 5.1.7 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_add_manufacturing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysetup',
            name='show_adjustment_history_before_after',
            field=models.BooleanField(default=True, help_text="Display 'Adjusted from X to Y' in Inventory Adjustment History", verbose_name='Show Adjustment History Before/After'),
        ),
    ]
