# Generated by Django 5.1.7 on 2026-01-20 09:47

import dimension.models
import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('dimension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('no', models.CharField(help_text='Record identifier (e.g., item no, customer no, location code)', max_length=255)),
                ('value_posting', models.CharField(choices=[('none', 'None'), ('code_mandatory', 'Code Mandatory'), ('same_code', 'Same Code')], default='none', help_text='Default dimension value posting rule', max_length=20)),
                ('table_caption', models.CharField(blank=True, help_text='Optional table caption for display', max_length=255)),
                ('dimension_code', models.ForeignKey(help_text='Dimension code (e.g., BRANCH)', on_delete=django.db.models.deletion.CASCADE, related_name='default_dimensions', to='dimension.dimension')),
                ('dimension_value', models.ForeignKey(default=dimension.models.get_default_dimension_value, help_text='Dimension value (e.g., Ntinda)', on_delete=django.db.models.deletion.CASCADE, related_name='default_dimensions', to='dimension.dimensionvalue')),
                ('table', models.ForeignKey(help_text='Target table for default dimension', limit_choices_to={'object_type': 'Table'}, on_delete=django.db.models.deletion.CASCADE, related_name='default_dimensions', to='base.objects')),
            ],
            options={
                'verbose_name': 'Default Dimension',
                'verbose_name_plural': 'Default Dimensions',
                'indexes': [models.Index(fields=['table', 'no'], name='dimension_d_table_i_139e7b_idx'), models.Index(fields=['dimension_code', 'dimension_value'], name='dimension_d_dimensi_6d7e67_idx')],
                'unique_together': {('table', 'no', 'dimension_code')},
            },
        ),
    ]
