# Generated by Django 5.1.7 on 2026-02-28 13:47

import postings.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0005_remove_dimensionvalue_dimension_type_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionvalue',
            name='dimension_type',
            field=models.CharField(choices=postings.enums.DimensionType.choices, max_length=255),
        ),
    ]
