# Generated by Django 5.1.7 on 2026-01-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedsalesinvoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used for this sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_sales_invoices', to='financials.paymentmethod', verbose_name='Payment Method'),
        ),
    ]
