# Generated by Django 5.1.7 on 2026-01-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_postedsalesinvoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedsalesinvoice',
            name='reversed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reversal Date'),
        ),
    ]
