# Generated by Django 5.1.7 on 2026-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_change_reversed_date_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedsalesinvoice',
            name='reversed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reversal Date'),
        ),
    ]
