# Generated by Django 5.1.7 on 2026-01-08 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_postedsalesinvoice_reversed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedsalesinvoice',
            name='invoice_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed discount amount in UGX', max_digits=10, verbose_name='Invoice Discount Amount'),
        ),
        migrations.AddField(
            model_name='postedsalesinvoice',
            name='invoice_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount percentage (0-100)', max_digits=5, verbose_name='Invoice Discount Percentage'),
        ),
        migrations.AddField(
            model_name='postedsalesinvoice',
            name='invoice_discount_type',
            field=models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', help_text='Type of invoice discount: fixed amount or percentage', max_length=20, null=True, verbose_name='Invoice Discount Type'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Fixed discount amount in UGX', max_digits=10, verbose_name='Invoice Discount Amount'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount percentage (0-100)', max_digits=5, verbose_name='Invoice Discount Percentage'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_discount_type',
            field=models.CharField(blank=True, choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default='amount', help_text='Type of invoice discount: fixed amount or percentage', max_length=20, null=True, verbose_name='Invoice Discount Type'),
        ),
        migrations.AddField(
            model_name='salesreceivable',
            name='enable_invoice_discounts',
            field=models.BooleanField(default=False, help_text='Allow users to enter invoice-level discounts on sales', verbose_name='Enable Invoice Discounts'),
        ),
    ]
