# Generated by Django 5.1.7 on 2026-01-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0002_defaultdimension'),
        ('financials', '0003_initial'),
        ('items', '0013_itemjournal_calculated_quantity_and_more'),
        ('resources', '0002_remove_resource_resources_r_dimensi_a67461_idx_and_more'),
        ('sales', '0005_add_invoice_discount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedsalesinvoiceline',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Resource on this line (when type=resource)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_sales_invoice_lines', to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='postedsalesinvoiceline',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('resource', 'Resource')], default='item', help_text='Whether this line is an Item or Resource (BC-style)', max_length=10, verbose_name='Line Type (Item/Resource)'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Resource sold on this line (when type=resource)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_lines', to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('resource', 'Resource')], default='item', help_text='Whether this line sells an Item or a Resource (BC-style)', max_length=10, verbose_name='Line Type (Item/Resource)'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Resource sold on this line (when type=resource)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('resource', 'Resource')], default='item', help_text='Whether this line sells an Item or a Resource (BC-style)', max_length=10, verbose_name='Line Type (Item/Resource)'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='items.item'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_sales_lines', to='items.location'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_lines', to='items.item'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_sales_order_lines', to='items.location'),
        ),
        migrations.AddIndex(
            model_name='postedsalesinvoiceline',
            index=models.Index(fields=['type'], name='posted_sales_line_type_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['type'], name='sales_line_type_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['type'], name='sales_order_line_type_idx'),
        ),
    ]
