# Generated by Django 5.1.7 on 2026-02-27 15:10

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_dimension_set_columns_if_missing(apps, schema_editor):
    tables = [
        "sales_customerledgerentry",
        "sales_detailedcustomerledgerentry",
        "sales_postedsalesinvoiceline",
        "sales_salescreditmemoline",
        "sales_salesinvoiceline",
        "sales_salesorderline",
    ]
    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            if not _pg_column_exists(cursor, table, "dimension_set_id"):
                cursor.execute(
                    f"""
                    ALTER TABLE {table}
                    ADD COLUMN dimension_set_id bigint NULL
                    REFERENCES dimension_dimensionset(id)
                    ON DELETE SET NULL
                    """
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0004_add_dimension_set_models"),
        ("sales", "0006_add_line_type_and_resource"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="customerledgerentry",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_ledger_entries",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AddField(
                    model_name="detailedcustomerledgerentry",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_customer_detailed_entries",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AddField(
                    model_name="postedsalesinvoiceline",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_sales_lines",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AddField(
                    model_name="salescreditmemoline",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_memo_lines",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoiceline",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_lines",
                        to="dimension.dimensionset",
                    ),
                ),
                migrations.AddField(
                    model_name="salesorderline",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_order_lines",
                        to="dimension.dimensionset",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_dimension_set_columns_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
