# Generated by Django 5.1.7 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0004_add_dimension_set_models'),
        ('sales', '0008_rename_dimension_1_to_global_dimension_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerentry',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='dimension.dimensionvalue', verbose_name='Global Dimension 1'),
        ),
        migrations.AlterField(
            model_name='detailedcustomerledgerentry',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, help_text='Global Dimension 1 value', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_customer_detailed_entries', to='dimension.dimensionvalue'),
        ),
        migrations.AlterField(
            model_name='salescreditmemoline',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_memo_lines', to='dimension.dimensionvalue', verbose_name='Global Dimension 1'),
        ),
    ]
