# Generated by Django 5.1.7 on 2026-03-01 07:22

import django.db.models.deletion
from django.db import migrations, models


def _get_first_branch_dimension_value_id(apps):
    """Get first branch DimensionValue id for backfill. Uses historical models."""
    GeneralLedgerSetup = apps.get_model("financials", "GeneralLedgerSetup")
    Dimension = apps.get_model("dimension", "Dimension")
    DimensionValue = apps.get_model("dimension", "DimensionValue")
    gl = GeneralLedgerSetup.objects.first()
    dim = None
    if gl and gl.global_dimension_1_id:
        dim = gl.global_dimension_1
    if not dim:
        dim = Dimension.objects.filter(code__iexact="BRANCH").first()
    if not dim:
        return None
    dv = DimensionValue.objects.filter(dimension_code=dim).order_by("code").first()
    return dv.id if dv else None


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_columns_and_backfill(apps, schema_editor):
    tables = [
        "sales_postedsalesinvoice",
        "sales_salescreditmemo",
        "sales_salesinvoice",
    ]
    col_specs = [
        ("dimension_set_id", "dimension_dimensionset"),
        ("global_dimension_1_id", "dimension_dimensionvalue"),
        ("global_dimension_2_id", "dimension_dimensionvalue"),
    ]
    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            for col, ref_table in col_specs:
                if not _pg_column_exists(cursor, table, col):
                    cursor.execute(
                        f"""
                        ALTER TABLE {table}
                        ADD COLUMN {col} bigint NULL
                        REFERENCES {ref_table}(id)
                        ON DELETE SET NULL
                        """
                    )

    branch_id = _get_first_branch_dimension_value_id(apps)
    if not branch_id:
        return
    tables = (
        "sales_salesinvoice",
        "sales_postedsalesinvoice",
        "sales_salescreditmemo",
        "sales_salesinvoiceline",
        "sales_postedsalesinvoiceline",
        "sales_salescreditmemoline",
    )
    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            if _pg_column_exists(cursor, table, "global_dimension_1_id"):
                cursor.execute(
                    f"UPDATE {table} SET global_dimension_1_id = %s "
                    f"WHERE global_dimension_1_id IS NULL",
                    [branch_id],
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0006_add_shortcut_dimensions_to_general_ledger_setup"),
        ("financials", "0008_add_enable_multiple_branches"),
        ("sales", "0009_alter_customerledgerentry_global_dimension_1_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="postedsalesinvoice",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_sales_invoice_headers",
                        to="dimension.dimensionset",
                        verbose_name="Dimension Set",
                    ),
                ),
                migrations.AddField(
                    model_name="postedsalesinvoice",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_sales_invoice_headers",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
                migrations.AddField(
                    model_name="postedsalesinvoice",
                    name="global_dimension_2",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_sales_invoice_headers_dim2",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 2",
                    ),
                ),
                migrations.AddField(
                    model_name="salescreditmemo",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_credit_memo_headers",
                        to="dimension.dimensionset",
                        verbose_name="Dimension Set",
                    ),
                ),
                migrations.AddField(
                    model_name="salescreditmemo",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_credit_memo_headers",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
                migrations.AddField(
                    model_name="salescreditmemo",
                    name="global_dimension_2",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_credit_memo_headers_dim2",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 2",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="dimension_set",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoice_headers",
                        to="dimension.dimensionset",
                        verbose_name="Dimension Set",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoice_headers",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="global_dimension_2",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoice_headers_dim2",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 2",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_columns_and_backfill, noop_reverse),
            ],
        ),
    ]
