# Generated by Django 5.1.7 on 2026-03-05 18:53

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_vat_business_posting_group_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _pg_column_exists(cursor, "sales_customer", "vat_business_posting_group_id"):
            cursor.execute(
                """
                ALTER TABLE sales_customer
                ADD COLUMN vat_business_posting_group_id varchar(255) NULL
                REFERENCES postings_vatbusinesspostinggroup(code)
                ON DELETE RESTRICT
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("postings", "0003_add_vat_posting_setup"),
        ("sales", "0010_add_header_dimensions"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="customer",
                    name="vat_business_posting_group",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="VAT posting group for this customer (when VAT is enabled).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="postings.vatbusinesspostinggroup",
                        verbose_name="VAT Bus. Posting Group",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_vat_business_posting_group_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
