# Generated by Django 5.1.7 on 2026-03-05 19:00

from decimal import Decimal

from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_vat_invoice_columns_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _pg_column_exists(cursor, "sales_salesinvoice", "prices_including_vat"):
            cursor.execute(
                """
                ALTER TABLE sales_salesinvoice
                ADD COLUMN prices_including_vat boolean NOT NULL DEFAULT false
                """
            )
        if not _pg_column_exists(cursor, "sales_salesinvoice", "total_vat_amount"):
            cursor.execute(
                """
                ALTER TABLE sales_salesinvoice
                ADD COLUMN total_vat_amount numeric(18,2) NOT NULL DEFAULT 0
                """
            )
        if not _pg_column_exists(cursor, "sales_salesinvoiceline", "vat_amount"):
            cursor.execute(
                """
                ALTER TABLE sales_salesinvoiceline
                ADD COLUMN vat_amount numeric(18,2) NOT NULL DEFAULT 0
                """
            )
        if not _pg_column_exists(cursor, "sales_salesinvoiceline", "vat_percent"):
            cursor.execute(
                """
                ALTER TABLE sales_salesinvoiceline
                ADD COLUMN vat_percent numeric(5,2) NULL DEFAULT 0
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_add_vat_posting_groups_to_master_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="salesinvoice",
                    name="prices_including_vat",
                    field=models.BooleanField(
                        default=False,
                        help_text="When enabled, unit prices and line amounts include VAT.",
                        verbose_name="Prices Including VAT",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoice",
                    name="total_vat_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Sum of line VAT amounts (computed).",
                        max_digits=18,
                        verbose_name="Total VAT Amount",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoiceline",
                    name="vat_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="VAT amount for this line (computed).",
                        max_digits=18,
                        verbose_name="VAT Amount",
                    ),
                ),
                migrations.AddField(
                    model_name="salesinvoiceline",
                    name="vat_percent",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="VAT percentage from VAT Posting Setup.",
                        max_digits=5,
                        null=True,
                        verbose_name="VAT %",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_vat_invoice_columns_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
