# Generated by Django 5.1.7 on 2026-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_add_shortcut_dimensions_to_general_ledger_setup'),
        ('financials', '0010_add_vat_entry'),
        ('sales', '0013_repair_posted_sales_invoice_line_drift'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', 'document_date'], name='sales_inv_status_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_at'], name='sales_inv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['payment_method'], name='sales_inv_pay_method_idx'),
        ),
    ]
