# Generated by Django 5.1.7 on 2026-04-01 14:05

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salesinvoice_sales_inv_status_doc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFavoriteSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('position', models.PositiveIntegerField(db_index=True, help_text='0-based row-major index in the favorites grid.')),
                ('item_system_id', models.CharField(blank=True, db_index=True, help_text='Item.system_id when the slot is occupied.', max_length=36, null=True)),
                ('item_no', models.CharField(blank=True, max_length=225, null=True)),
                ('item_name', models.CharField(blank=True, max_length=225, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_favorite_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales favorite slot',
                'verbose_name_plural': 'Sales favorite slots',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('user', 'position'), name='sales_salesfavoriteslot_user_position_uniq')],
            },
        ),
    ]
