# Generated by Django 5.1.7 on 2026-06-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('sales', '0019_salesorder_customer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderline',
            name='item',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sales_order_lines',
                to='items.item',
            ),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='location_code',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='location_sales_order_lines',
                to='items.location',
            ),
        ),
    ]
