# Generated by Django 5.1.7 on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Idempotent repair for schemas where sales_salesinvoiceline.item_id (and
    location_code_id) are still NOT NULL even though 0006 is recorded as applied.
    Mirrors 0020_salesorderline_item_nullable for invoice lines.
    """

    dependencies = [
        ('items', '0001_initial'),
        ('sales', '0020_salesorderline_item_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE IF EXISTS sales_salesinvoiceline
                    ALTER COLUMN item_id DROP NOT NULL;

                ALTER TABLE IF EXISTS sales_salesinvoiceline
                    ALTER COLUMN location_code_id DROP NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sales_lines',
                to='items.item',
            ),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='location_code',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='location_sales_lines',
                to='items.location',
            ),
        ),
    ]
