# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Object Type',
                'verbose_name_plural': 'Object Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('object_type', models.CharField(choices=[('Table', 'Table'), ('Page', 'Page'), ('Report', 'Report'), ('Query', 'Query'), ('XMLport', 'XMLport'), ('Enum', 'Enum'), ('MenuSuite', 'MenuSuite')], help_text='Type of the object', max_length=100)),
                ('object_id', models.IntegerField(help_text='Unique identifier for the object', primary_key=True, serialize=False)),
                ('object_name', models.CharField(help_text='Name of the object', max_length=255, unique=True)),
                ('object_caption', models.CharField(help_text='Caption/description of the object', max_length=255)),
                ('object_subtype', models.CharField(choices=[('Temporary', 'Temporary'), ('Permanent', 'Permanent'), ('System', 'System'), ('Custom', 'Custom'), ('ThirdParty', 'ThirdParty')], default='Custom', help_text='Subtype classification of the object', max_length=50)),
                ('app_label', models.CharField(default='None', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_permission', models.BooleanField(default=True, help_text='If False, object is accessible to all users')),
                ('related_model', models.CharField(blank=True, help_text="Full model path (e.g., 'customers.Customer')", max_length=100, null=True)),
                ('object_type_ref', models.ForeignKey(blank=True, help_text='Link to ObjectType for permission system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_objects', to='base.objecttype')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
                'ordering': ['object_type', 'object_id'],
                'unique_together': {('object_type', 'object_id')},
            },
        ),
    ]
