# Generated by Django 5.1.7 on 2026-05-22 17:19

import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('device_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('client_type', models.CharField(choices=[('desktop', 'Desktop'), ('web', 'Web'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Device',
                'verbose_name_plural': 'Sync Devices',
                'db_table': 'sync_device',
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('event_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=36)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Event',
                'verbose_name_plural': 'Sync Events',
                'db_table': 'sync_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('item_system_id', models.CharField(db_index=True, max_length=36)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('item_no', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Inventory Snapshot',
                'verbose_name_plural': 'Inventory Snapshots',
                'db_table': 'sync_inventory_snapshot',
                'unique_together': {('item_system_id', 'branch_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('device_id', models.CharField(db_index=True, max_length=36)),
                ('resource', models.CharField(db_index=True, max_length=64)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('updated_since', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Cursor',
                'verbose_name_plural': 'Sync Cursors',
                'db_table': 'sync_cursor',
                'unique_together': {('device_id', 'resource', 'branch_id')},
            },
        ),
    ]
