# Generated by Django 5.1.7 on 2025-12-12 02:59

import purchases.models
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document No.')),
                ('posting_date', models.DateField(blank=True, default=purchases.models.get_today, null=True, verbose_name='Posting Date')),
                ('document_type', models.CharField(choices=[('Expense', 'Expense'), ('Refund', 'Refund'), ('Adjustment', 'Adjustment')], default='Expense', max_length=20, verbose_name='Document Type')),
                ('external_document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='External Document No.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Posted', 'Posted'), ('Reversed', 'Reversed')], default='Open', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('transaction_no', models.CharField(blank=True, help_text='Transaction number for grouping related entries', max_length=50, null=True, verbose_name='Transaction No.')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-posting_date', '-document_no'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Short code for the category (auto-uppercase)', max_length=32, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Display name shown to users when selecting a category', max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description surfaced in tooltips/modals', null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier for frontend cards/chips', max_length=64, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category can be selected', verbose_name='Active')),
                ('is_system', models.BooleanField(default=True, help_text='System categories are seeded and protected from deletion', verbose_name='System Category')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(blank=True, help_text='Short code for the expense type (auto-uppercase)', max_length=10, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Display name for the expense type', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the expense type', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this expense type is available for use', verbose_name='Active')),
                ('is_user_defined', models.BooleanField(default=False, help_text='Indicates whether this type was created by an end user', verbose_name='User Defined')),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['name'],
            },
        ),
    ]
