# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('financials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balancing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_balancing_entries', to='financials.g_laccount', verbose_name='Balancing Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financials.g_laccount', verbose_name='G/L Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financials.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='expense',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Posted By'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='default_gl_account',
            field=models.ForeignKey(blank=True, help_text='Primary G/L account used when expense types do not override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='financials.g_laccount', verbose_name='Default G/L Account'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Financial category that controls the default G/L account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_types', to='expenses.expensecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='Optional override G/L account for this expense type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_types', to='financials.g_laccount', verbose_name='Override G/L Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensetype', verbose_name='Expense Type'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['code'], name='expenses_ex_code_87d722_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['is_active'], name='expenses_ex_is_acti_8ba8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetype',
            index=models.Index(fields=['code'], name='expenses_ex_code_3de671_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetype',
            index=models.Index(fields=['name'], name='expenses_ex_name_1b10b3_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetype',
            index=models.Index(fields=['is_active'], name='expenses_ex_is_acti_d5d434_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetype',
            index=models.Index(fields=['category'], name='expenses_ex_categor_4264ef_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['posting_date', 'status'], name='expense_report_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'posting_date'], name='expense_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['posting_date'], name='expenses_ex_posting_9a8146_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['document_no'], name='expenses_ex_documen_67a2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='expenses_ex_expense_3c4432_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['gl_account'], name='expenses_ex_gl_acco_8fac12_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['balancing_account'], name='expenses_ex_balanci_374757_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_method'], name='expenses_ex_payment_c08d02_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['posted_at'], name='expenses_ex_posted__3edca8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['transaction_no'], name='expenses_ex_transac_1d3885_idx'),
        ),
    ]
