# Generated by Django 5.1.7 on 2026-03-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0006_add_shortcut_dimensions_to_general_ledger_setup'),
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dimension_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_headers', to='dimension.dimensionset', verbose_name='Dimension Set'),
        ),
        migrations.AddField(
            model_name='expense',
            name='global_dimension_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_headers', to='dimension.dimensionvalue', verbose_name='Global Dimension 1'),
        ),
        migrations.AddField(
            model_name='expense',
            name='global_dimension_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_headers_dim2', to='dimension.dimensionvalue', verbose_name='Global Dimension 2'),
        ),
    ]
