# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import purchases.models
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document No.')),
                ('posting_date', models.DateField(blank=True, default=purchases.models.get_today, null=True, verbose_name='Posting Date')),
                ('document_type', models.CharField(choices=[('Payment', 'Payment'), ('Invoice', 'Invoice'), ('Credit Memo', 'Credit Memo'), ('Finance Charge Memo', 'Finance Charge Memo'), ('Reminder', 'Reminder'), ('Refund', 'Refund')], default='Payment', max_length=20, verbose_name='Document Type')),
                ('external_document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='External Document No.')),
                ('account_type', models.CharField(blank=True, choices=[('', '-- Select Account Type --'), ('Customer', 'Customer'), ('Vendor', 'Vendor'), ('G/L Account', 'G/L Account')], max_length=20, null=True, verbose_name='Account Type')),
                ('account_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Account Object ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('bal_account_type', models.CharField(blank=True, choices=[('', '-- Select Account Type --'), ('Customer', 'Customer'), ('Vendor', 'Vendor'), ('G/L Account', 'G/L Account')], max_length=20, null=True, verbose_name='Balancing Account Type')),
                ('bal_account_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Balancing Account Object ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Posted', 'Posted'), ('Void', 'Void'), ('Cancelled', 'Cancelled')], default='Open', max_length=20, verbose_name='Status')),
                ('application_status', models.CharField(choices=[('Applied', 'Applied'), ('Unapplied', 'Unapplied'), ('Partially Applied', 'Partially Applied')], default='Unapplied', max_length=20, verbose_name='Application Status')),
                ('applies_to_doc_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Applies To Document Type')),
                ('applies_to_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Applies To Object ID')),
                ('account_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_journal_accounts', to='contenttypes.contenttype', verbose_name='Account Content Type')),
                ('applies_to_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_journal_applies_to', to='contenttypes.contenttype', verbose_name='Applies To Content Type')),
                ('bal_account_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_journal_balancing_accounts', to='contenttypes.contenttype', verbose_name='Balancing Account Content Type')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_journals', to='financials.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment Journal Entry',
                'verbose_name_plural': 'Payment Journal Entries',
                'ordering': ['-posting_date', '-document_no'],
                'indexes': [models.Index(fields=['posting_date'], name='payments_pa_posting_8e0458_idx'), models.Index(fields=['document_no'], name='payments_pa_documen_f5feab_idx'), models.Index(fields=['account_type'], name='payments_pa_account_e0dccc_idx'), models.Index(fields=['bal_account_type'], name='payments_pa_bal_acc_0c44f7_idx'), models.Index(fields=['status'], name='payments_pa_status_7367ad_idx'), models.Index(fields=['application_status'], name='payments_pa_applica_95e4c3_idx'), models.Index(fields=['account_content_type', 'account_object_id'], name='payments_pa_account_f29341_idx'), models.Index(fields=['bal_account_content_type', 'bal_account_object_id'], name='payments_pa_bal_acc_ba1011_idx'), models.Index(fields=['applies_to_content_type', 'applies_to_object_id'], name='payments_pa_applies_7a563a_idx'), models.Index(fields=['payment_method'], name='payments_pa_payment_dc7c40_idx')],
            },
        ),
    ]
