# Generated by Django 5.1.7 on 2026-03-13 08:03

import django.db.models.deletion
import utils.utils
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _tenant_table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = %s
            """,
            [table_name],
        )
        return cursor.fetchone() is not None


def create_restaurant_tables_if_missing(apps, schema_editor):
    """Create restaurant_management tables only when missing (tenant drift).

    Must use historical models from ``apps`` so schema matches this migration
    state. Importing live models would include later fields (e.g. FK to models
    added in 0002) and break ``create_model`` with missing referenced tables.
    """
    Floor = apps.get_model("restaurant_management", "Floor")
    MenuCategory = apps.get_model("restaurant_management", "MenuCategory")
    Table = apps.get_model("restaurant_management", "Table")
    MenuItem = apps.get_model("restaurant_management", "MenuItem")
    Reservation = apps.get_model("restaurant_management", "Reservation")
    RestaurantOrder = apps.get_model("restaurant_management", "RestaurantOrder")
    RestaurantOrderItem = apps.get_model("restaurant_management", "RestaurantOrderItem")

    order = (
        Floor,
        MenuCategory,
        Table,
        MenuItem,
        Reservation,
        RestaurantOrder,
        RestaurantOrderItem,
    )
    for model in order:
        if _tenant_table_exists(schema_editor, model._meta.db_table):
            continue
        schema_editor.create_model(model)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0024_add_vat_posting_groups_to_master_data"),
        ("sales", "0012_add_vat_fields_to_invoices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Floor",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "no",
                            models.CharField(
                                db_index=True,
                                help_text="Floor number/code",
                                max_length=50,
                                unique=True,
                                verbose_name="No.",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(max_length=100, verbose_name="Name"),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True, null=True, verbose_name="Description"
                            ),
                        ),
                        (
                            "display_order",
                            models.IntegerField(default=0, verbose_name="Display Order"),
                        ),
                    ],
                    options={
                        "verbose_name": "Floor",
                        "verbose_name_plural": "Floors",
                        "ordering": ["display_order", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="MenuCategory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "no",
                            models.CharField(
                                db_index=True,
                                help_text="Category code",
                                max_length=50,
                                unique=True,
                                verbose_name="No.",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(max_length=100, verbose_name="Name"),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True, null=True, verbose_name="Description"
                            ),
                        ),
                        (
                            "display_order",
                            models.IntegerField(default=0, verbose_name="Display Order"),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="Active"),
                        ),
                    ],
                    options={
                        "verbose_name": "Menu Category",
                        "verbose_name_plural": "Menu Categories",
                        "ordering": ["display_order", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="MenuItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True,
                                default="",
                                help_text="Extended description for menu",
                                verbose_name="Description",
                            ),
                        ),
                        (
                            "image",
                            models.ImageField(
                                blank=True,
                                null=True,
                                upload_to="restaurant/menu_items/",
                                verbose_name="Image",
                            ),
                        ),
                        (
                            "is_available",
                            models.BooleanField(default=True, verbose_name="Available"),
                        ),
                        (
                            "preparation_time",
                            models.IntegerField(
                                default=15,
                                help_text="Average prep time",
                                verbose_name="Preparation Time (minutes)",
                            ),
                        ),
                        (
                            "is_featured",
                            models.BooleanField(default=False, verbose_name="Featured"),
                        ),
                        (
                            "spice_level",
                            models.IntegerField(
                                default=0,
                                help_text="0-5 spice level",
                                verbose_name="Spice Level",
                            ),
                        ),
                        (
                            "dietary_info",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List: vegetarian, vegan, gluten_free, etc.",
                                verbose_name="Dietary Info",
                            ),
                        ),
                        (
                            "allergens",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List of allergens",
                                verbose_name="Allergens",
                            ),
                        ),
                        (
                            "available_sides",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List of available side options (e.g., ['fries', 'naan', 'rice', 'salad'])",
                                verbose_name="Available Sides",
                            ),
                        ),
                        (
                            "display_order",
                            models.IntegerField(default=0, verbose_name="Display Order"),
                        ),
                        (
                            "category",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="menu_items",
                                to="restaurant_management.menucategory",
                            ),
                        ),
                        (
                            "item",
                            models.OneToOneField(
                                help_text="Links to existing POS item",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="menu_item",
                                to="items.item",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Menu Item",
                        "verbose_name_plural": "Menu Items",
                        "ordering": ["category", "display_order", "item__item_name"],
                    },
                ),
                migrations.CreateModel(
                    name="Reservation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "no",
                            models.CharField(
                                db_index=True,
                                help_text="Reservation number",
                                max_length=50,
                                unique=True,
                                verbose_name="No.",
                            ),
                        ),
                        (
                            "reservation_date",
                            models.DateTimeField(verbose_name="Reservation Date"),
                        ),
                        (
                            "party_size",
                            models.IntegerField(default=2, verbose_name="Party Size"),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("confirmed", "Confirmed"),
                                    ("seated", "Seated"),
                                    ("cancelled", "Cancelled"),
                                    ("no_show", "No Show"),
                                    ("completed", "Completed"),
                                ],
                                default="pending",
                                max_length=20,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "special_requests",
                            models.TextField(
                                blank=True, null=True, verbose_name="Special Requests"
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(blank=True, null=True, verbose_name="Notes"),
                        ),
                        (
                            "customer",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="restaurant_reservations",
                                to="sales.customer",
                            ),
                        ),
                        (
                            "waiter",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="reservations",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Reservation",
                        "verbose_name_plural": "Reservations",
                        "ordering": ["-reservation_date"],
                    },
                ),
                migrations.CreateModel(
                    name="RestaurantOrder",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "no",
                            models.CharField(
                                db_index=True,
                                help_text="Order number",
                                max_length=50,
                                unique=True,
                                verbose_name="No.",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("new", "New"),
                                    ("in_progress", "In Progress"),
                                    ("ready", "Ready"),
                                    ("served", "Served"),
                                    ("completed", "Completed"),
                                    ("cancelled", "Cancelled"),
                                ],
                                default="new",
                                max_length=20,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "order_type",
                            models.CharField(
                                choices=[
                                    ("dine_in", "Dine In"),
                                    ("takeout", "Takeout"),
                                    ("delivery", "Delivery"),
                                ],
                                default="dine_in",
                                max_length=20,
                                verbose_name="Order Type",
                            ),
                        ),
                        (
                            "total_amount",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                max_digits=10,
                                verbose_name="Total Amount",
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(blank=True, null=True, verbose_name="Notes"),
                        ),
                        (
                            "customer",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="restaurant_orders",
                                to="sales.customer",
                            ),
                        ),
                        (
                            "reservation",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="orders",
                                to="restaurant_management.reservation",
                            ),
                        ),
                        (
                            "sales_invoice",
                            models.ForeignKey(
                                blank=True,
                                help_text="Link to POS invoice when order is billed",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="restaurant_orders",
                                to="sales.salesinvoice",
                            ),
                        ),
                        (
                            "waiter",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="restaurant_orders",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Restaurant Order",
                        "verbose_name_plural": "Restaurant Orders",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="RestaurantOrderItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "quantity",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("1.00"),
                                max_digits=10,
                                verbose_name="Quantity",
                            ),
                        ),
                        (
                            "unit_price",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                max_digits=10,
                                verbose_name="Unit Price",
                            ),
                        ),
                        (
                            "total_price",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                max_digits=10,
                                verbose_name="Total Price",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("preparing", "Preparing"),
                                    ("ready", "Ready"),
                                    ("served", "Served"),
                                    ("cancelled", "Cancelled"),
                                ],
                                default="pending",
                                max_length=20,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "special_instructions",
                            models.TextField(
                                blank=True, null=True, verbose_name="Special Instructions"
                            ),
                        ),
                        (
                            "selected_sides",
                            models.JSONField(
                                blank=True,
                                default=list,
                                help_text="List of selected side items (e.g., ['fries', 'naan', 'rice'])",
                                verbose_name="Selected Sides",
                            ),
                        ),
                        (
                            "spice_level",
                            models.IntegerField(
                                blank=True,
                                help_text="Customer-selected spice level (0-5). If null, uses menu item default.",
                                null=True,
                                verbose_name="Spice Level",
                            ),
                        ),
                        (
                            "preparation_time",
                            models.IntegerField(
                                blank=True,
                                help_text="Estimated preparation time",
                                null=True,
                                verbose_name="Preparation Time (minutes)",
                            ),
                        ),
                        (
                            "item",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="restaurant_order_items",
                                to="items.item",
                            ),
                        ),
                        (
                            "order",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="order_items",
                                to="restaurant_management.restaurantorder",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Restaurant Order Item",
                        "verbose_name_plural": "Restaurant Order Items",
                        "ordering": ["order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="Table",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                db_index=True,
                                verbose_name="Created At",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                        ),
                        (
                            "system_id",
                            utils.utils.UUIField(
                                db_index=True,
                                default=uuid.uuid4,
                                editable=False,
                                max_length=36,
                                unique=True,
                                verbose_name="System ID",
                            ),
                        ),
                        (
                            "no",
                            models.CharField(
                                db_index=True,
                                help_text="Table number",
                                max_length=50,
                                unique=True,
                                verbose_name="No.",
                            ),
                        ),
                        (
                            "table_number",
                            models.CharField(max_length=50, verbose_name="Table Number"),
                        ),
                        (
                            "capacity",
                            models.IntegerField(default=4, verbose_name="Capacity"),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("available", "Available"),
                                    ("occupied", "Occupied"),
                                    ("reserved", "Reserved"),
                                    ("cleaning", "Cleaning"),
                                    ("maintenance", "Maintenance"),
                                ],
                                default="available",
                                max_length=20,
                                verbose_name="Status",
                            ),
                        ),
                        (
                            "shape",
                            models.CharField(
                                choices=[
                                    ("round", "Round"),
                                    ("square", "Square"),
                                    ("rectangular", "Rectangular"),
                                    ("booth", "Booth"),
                                ],
                                default="round",
                                max_length=20,
                                verbose_name="Shape",
                            ),
                        ),
                        (
                            "location_x",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                help_text="X position for floor plan",
                                max_digits=10,
                                verbose_name="Location X",
                            ),
                        ),
                        (
                            "location_y",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                help_text="Y position for floor plan",
                                max_digits=10,
                                verbose_name="Location Y",
                            ),
                        ),
                        (
                            "notes",
                            models.TextField(blank=True, null=True, verbose_name="Notes"),
                        ),
                        (
                            "floor",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="tables",
                                to="restaurant_management.floor",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Table",
                        "verbose_name_plural": "Tables",
                        "ordering": ["floor", "table_number"],
                    },
                ),
                migrations.AddField(
                    model_name="restaurantorder",
                    name="table",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Table is required for Dine In orders, optional for Takeaway/Delivery",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="restaurant_management.table",
                    ),
                ),
                migrations.AddField(
                    model_name="reservation",
                    name="table",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Table can be assigned later",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="restaurant_management.table",
                    ),
                ),
            ],
            database_operations=[],
        ),
        # Run after state_operations above so ``apps`` includes restaurant_management models
        # (RunPython inside SeparateDatabaseAndState only sees pre-migration ``from_state``).
        migrations.RunPython(
            create_restaurant_tables_if_missing,
            noop_reverse,
        ),
    ]
