# Generated by Django 5.1.7 on 2026-04-14 15:54

import django.db.models.deletion
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


def _tenant_table_exists(schema_editor, table_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = %s
            """,
            [table_name],
        )
        return cursor.fetchone() is not None


def ensure_0001_restaurant_tables_if_missing(apps, schema_editor):
    """If 0001 was faked or failed before RunPython, base tables may be missing.

    Mirrors ``0001_initial.create_restaurant_tables_if_missing`` so 0002 ALTERs
    run against real tables.
    """
    Floor = apps.get_model("restaurant_management", "Floor")
    MenuCategory = apps.get_model("restaurant_management", "MenuCategory")
    Table = apps.get_model("restaurant_management", "Table")
    MenuItem = apps.get_model("restaurant_management", "MenuItem")
    Reservation = apps.get_model("restaurant_management", "Reservation")
    RestaurantOrder = apps.get_model("restaurant_management", "RestaurantOrder")
    RestaurantOrderItem = apps.get_model("restaurant_management", "RestaurantOrderItem")

    order = (
        Floor,
        MenuCategory,
        Table,
        MenuItem,
        Reservation,
        RestaurantOrder,
        RestaurantOrderItem,
    )
    for model in order:
        if _tenant_table_exists(schema_editor, model._meta.db_table):
            continue
        schema_editor.create_model(model)


def noop_reverse_ensure(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_item_manual_unit_cost_alter_item_unit_price'),
        ('restaurant_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_0001_restaurant_tables_if_missing,
            noop_reverse_ensure,
        ),
        migrations.CreateModel(
            name='MenuLayoutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(default='Page', max_length=100)),
            ],
            options={
                'ordering': ['menu', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('selection_mode', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=20)),
                ('min_selections', models.PositiveIntegerField(default=0)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='covers',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests/seats for this order/check', verbose_name='Covers'),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='course',
            field=models.CharField(choices=[('straight_fire', 'Straight Fire'), ('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert')], default='straight_fire', max_length=20, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='fire_state',
            field=models.CharField(choices=[('hold', 'Hold'), ('fire', 'Fire')], default='hold', max_length=10, verbose_name='Fire State'),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='fired_at',
            field=models.DateTimeField(blank=True, help_text='When item was sent/fired to production', null=True, verbose_name='Fired At'),
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='seat_no',
            field=models.PositiveIntegerField(blank=True, help_text='Seat assignment for service and split logic', null=True, verbose_name='Seat No.'),
        ),
        migrations.CreateModel(
            name='MenuDisplayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='restaurant_management.menudisplaygroup')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_groups', to='restaurant_management.servicemenu')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuLayoutTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('row_span', models.PositiveIntegerField(default=1)),
                ('col_span', models.PositiveIntegerField(default=1)),
                ('display_order', models.IntegerField(default=0)),
                ('display_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_tiles', to='restaurant_management.menudisplaygroup')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_tiles', to='restaurant_management.menuitem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='restaurant_management.menulayoutpage')),
            ],
            options={
                'ordering': ['page', 'display_order', 'row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurant_management.modifiergroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrderActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('action_type', models.CharField(choices=[('open_table', 'Open Table'), ('fire_items', 'Fire Items'), ('repeat_item', 'Repeat Item'), ('delete_or_cancel_item', 'Delete/Cancel Item'), ('split_check', 'Split Check'), ('move_items', 'Move Items'), ('void_check', 'Void Check'), ('comp_check', 'Comp Check'), ('clear_new_items', 'Clear New Items')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='restaurant_management.restaurantorder')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='restaurant_management.restaurantorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(default='Check', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('seat_numbers', models.JSONField(blank=True, default=list)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_voided', models.BooleanField(default=False)),
                ('is_comped', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='restaurant_management.restaurantorder')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restaurantorderitem',
            name='restaurant_check',
            field=models.ForeignKey(blank=True, help_text='Optional check segment this item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='restaurant_management.restaurantcheck'),
        ),
        migrations.AddField(
            model_name='menulayoutpage',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='restaurant_management.servicemenu'),
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='restaurant_management.menuitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant_management.modifiergroup')),
            ],
            options={
                'ordering': ['menu_item', 'display_order'],
                'unique_together': {('menu_item', 'modifier_group')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_modifiers', to='restaurant_management.modifiergroup')),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_modifiers', to='restaurant_management.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant_management.restaurantorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='restaurant__created_cc10c4_idx'), models.Index(fields=['system_id'], name='restaurant__system__3ccf98_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='menulayoutpage',
            unique_together={('menu', 'page_number')},
        ),
        migrations.CreateModel(
            name='ServiceMenuLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('is_default', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_service_menus', to='items.location')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='restaurant_management.servicemenu')),
            ],
            options={
                'unique_together': {('menu', 'location')},
            },
        ),
    ]
