# Generated by Django 5.1.7 on 2026-04-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0028_not_null_branch_dimensions"),
        ("restaurant_management", "0017_not_null_branch_dimensions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["name"],
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
        migrations.AlterModelOptions(
            name="menulocation",
            options={
                "verbose_name": "Menu location",
                "verbose_name_plural": "Menu locations",
            },
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="display_group",
            field=models.ForeignKey(
                blank=True,
                help_text="POS display group for this menu (one group per item; null = Home screen on the top-level grid).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="restaurant_management.menudisplaygroup",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, this catalog row is scoped to that POS menu (Menu Builder list).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="restaurant_management.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="tile_accent_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preset key or #RRGGBB for POS tile styling when the layout tile has no accent override.",
                max_length=16,
                verbose_name="Tile accent color",
            ),
        ),
        migrations.AlterField(
            model_name="menulocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_location_links",
                to="items.location",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantorderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Sent"),
                    ("ready", "Ready"),
                    ("served", "Served"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("square", "Square"),
                    ("rectangular", "Rectangular"),
                    ("booth", "Booth"),
                    ("oval", "Oval"),
                ],
                default="round",
                max_length=20,
                verbose_name="Shape",
            ),
        ),
    ]
