# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_management", "0018_model_sync_menu_and_pos_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantorderitem",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When kitchen staff started preparation (pending → preparing)",
                null=True,
                verbose_name="Started At",
            ),
        ),
    ]
