from django.db import models
from django.utils.translation import gettext_lazy as _
from utils.utils import BaseModel


class ScheduledReport(BaseModel):
    """
    Model for scheduling automated report generation and delivery.
    Reports can be scheduled to run daily, weekly, or monthly and
    delivered to specified recipients via email.
    """

    REPORT_TYPE_CHOICES = [
        ("daily_profit", "Daily Profit Report"),
        ("weekly_summary", "Weekly Summary Report"),
        ("monthly_summary", "Monthly Summary Report"),
        ("product_profitability", "Product Profitability Report"),
        ("expense_breakdown", "Expense Breakdown Report"),
    ]

    FREQUENCY_CHOICES = [
        ("daily", "Daily"),
        ("weekly", "Weekly"),
        ("monthly", "Monthly"),
    ]

    FORMAT_CHOICES = [
        ("pdf", "PDF"),
        ("csv", "CSV"),
        ("excel", "Excel"),
    ]

    name = models.CharField(
        _("Report Name"),
        max_length=255,
        help_text=_("Descriptive name for this scheduled report"),
    )
    report_type = models.CharField(
        _("Report Type"), max_length=50, choices=REPORT_TYPE_CHOICES
    )
    frequency = models.CharField(
        _("Frequency"), max_length=20, choices=FREQUENCY_CHOICES
    )
    recipients = models.JSONField(
        _("Recipients"), help_text=_("List of email addresses to send the report to")
    )
    export_format = models.CharField(
        _("Export Format"), max_length=10, choices=FORMAT_CHOICES, default="pdf"
    )
    filters = models.JSONField(
        _("Filters"),
        default=dict,
        blank=True,
        help_text=_("Stored filter parameters (date ranges, categories, etc.)"),
    )
    is_active = models.BooleanField(_("Active"), default=True)
    last_run = models.DateTimeField(_("Last Run"), null=True, blank=True)
    next_run = models.DateTimeField(_("Next Run"))
    created_by = models.ForeignKey(
        "authentication.CustomUser",
        on_delete=models.CASCADE,
        related_name="scheduled_reports",
        verbose_name=_("Created By"),
    )

    class Meta:
        verbose_name = _("Scheduled Report")
        verbose_name_plural = _("Scheduled Reports")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["report_type"]),
            models.Index(fields=["frequency"]),
            models.Index(fields=["is_active", "next_run"]),
            models.Index(fields=["created_by"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.get_frequency_display()})"


class ReportLog(BaseModel):
    """
    Audit trail and performance tracking for report generation.
    Logs every report generation with execution time and filters applied.
    """

    report_type = models.CharField(_("Report Type"), max_length=50)
    generated_by = models.ForeignKey(
        "authentication.CustomUser",
        on_delete=models.SET_NULL,
        null=True,
        related_name="report_logs",
        verbose_name=_("Generated By"),
    )
    generated_at = models.DateTimeField(_("Generated At"), auto_now_add=True)
    filters_applied = models.JSONField(
        _("Filters Applied"), help_text=_("Filters used for this report generation")
    )
    export_format = models.CharField(
        _("Export Format"),
        max_length=10,
        null=True,
        blank=True,
        help_text=_("Format if exported (pdf, csv, excel)"),
    )
    execution_time_ms = models.IntegerField(
        _("Execution Time (ms)"), help_text=_("Time taken to generate the report")
    )
    cached = models.BooleanField(
        _("Cached"), default=False, help_text=_("Whether data was served from cache")
    )
    scheduled_report = models.ForeignKey(
        ScheduledReport,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="execution_logs",
        verbose_name=_("Scheduled Report"),
    )
    ip_address = models.GenericIPAddressField(_("IP Address"), null=True, blank=True)

    class Meta:
        verbose_name = _("Report Log")
        verbose_name_plural = _("Report Logs")
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["report_type"]),
            models.Index(fields=["generated_by"]),
            models.Index(fields=["generated_at"]),
            models.Index(fields=["scheduled_report"]),
        ]

    def __str__(self):
        return f"{self.report_type} - {self.generated_at.strftime('%Y-%m-%d %H:%M')}"
