# Generated by Django 5.1.7 on 2025-12-28 08:12

import django.db.models.deletion
import loans.models
import utils.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('loan_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Loan No.')),
                ('loan_type', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('SACCO', 'SACCO'), ('Individual', 'Individual')], max_length=20, null=True, verbose_name='Loan Type')),
                ('lender_name', models.CharField(max_length=255, verbose_name='Lender Name')),
                ('loan_amount', models.IntegerField(verbose_name='Loan Amount')),
                ('disbursement_date', models.DateField(blank=True, default=loans.models.get_today, null=True, verbose_name='Disbursement Date')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage', max_digits=5, verbose_name='Interest Rate (%)')),
                ('repayment_period', models.IntegerField(help_text='Number of months for loan repayment', verbose_name='Repayment Period (Months)')),
                ('repayment_account', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=20, null=True, verbose_name='Repayment Account')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Purpose')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Posted', 'Posted'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20, verbose_name='Status')),
                ('posted', models.BooleanField(default=False, verbose_name='Posted')),
                ('posted_date', models.DateField(blank=True, null=True, verbose_name='Posted Date')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_loans', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-disbursement_date', '-loan_no'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('repayment_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Repayment No.')),
                ('payment_date', models.DateField(blank=True, default=loans.models.get_today, null=True, verbose_name='Payment Date')),
                ('amount_paid', models.IntegerField(verbose_name='Amount Paid')),
                ('principal_amount', models.IntegerField(default=0, help_text='Calculated automatically', verbose_name='Principal Amount')),
                ('interest_amount', models.IntegerField(default=0, help_text='Calculated automatically', verbose_name='Interest Amount')),
                ('payment_method', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Cash', 'Cash')], max_length=20, null=True, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Open', max_length=20, verbose_name='Status')),
                ('posted', models.BooleanField(default=False, verbose_name='Posted')),
                ('posted_date', models.DateField(blank=True, null=True, verbose_name='Posted Date')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan', verbose_name='Loan')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_loan_repayments', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-payment_date', '-repayment_no'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_no'], name='loans_loan_loan_no_bcc494_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['disbursement_date'], name='loans_loan_disburs_33922a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['posted'], name='loans_loan_posted_db8a44_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['repayment_no'], name='loans_loanr_repayme_80c4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['payment_date'], name='loans_loanr_payment_f7c4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['status'], name='loans_loanr_status_763b96_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['posted'], name='loans_loanr_posted_2453c7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan'], name='loans_loanr_loan_id_83acb8_idx'),
        ),
    ]
