# Generated by Django 5.1.7 on 2025-12-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Required when Repayment Account is 'Bank'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='bank_account.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Required when Payment Method is 'Bank'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='bank_account.bankaccount', verbose_name='Bank Account'),
        ),
    ]
