# Generated by Django 5.1.7 on 2026-01-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_initial'),
        ('loans', '0002_loan_bank_account_loanrepayment_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Required when Repayment Account is 'Bank/Mobile Money'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='bank_account.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_account',
            field=models.CharField(blank=True, choices=[('Bank/Mobile Money', 'Bank/Mobile Money'), ('Cash', 'Cash')], max_length=20, null=True, verbose_name='Repayment Account'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Required when Payment Method is 'Bank/Mobile Money'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='bank_account.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank/Mobile Money', 'Bank/Mobile Money'), ('Cash', 'Cash')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
