# Generated by Django 5.1.7 on 2026-03-07 06:39

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def add_global_dimension_columns_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not _pg_column_exists(cursor, "loans_loan", "global_dimension_1_id"):
            cursor.execute(
                """
                ALTER TABLE loans_loan
                ADD COLUMN global_dimension_1_id bigint NULL
                REFERENCES dimension_dimensionvalue(id)
                ON DELETE SET NULL
                """
            )
        if not _pg_column_exists(cursor, "loans_loanrepayment", "global_dimension_1_id"):
            cursor.execute(
                """
                ALTER TABLE loans_loanrepayment
                ADD COLUMN global_dimension_1_id bigint NULL
                REFERENCES dimension_dimensionvalue(id)
                ON DELETE SET NULL
                """
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0006_add_shortcut_dimensions_to_general_ledger_setup"),
        ("loans", "0003_alter_loan_bank_account_alter_loan_repayment_account_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="loan",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1 (Branch)",
                    ),
                ),
                migrations.AddField(
                    model_name="loanrepayment",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_repayments",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1 (Branch)",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_global_dimension_columns_if_missing,
                    noop_reverse,
                ),
            ],
        ),
    ]
