# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('name', models.CharField(help_text='Name of the upload template', max_length=50, unique=True)),
                ('template_file', models.FileField(help_text='File of the upload template', upload_to='upload_templates/')),
            ],
            options={
                'verbose_name': 'Upload Template',
                'verbose_name_plural': 'Upload Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Configuration package identifier', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('package_name', models.CharField(help_text='Name of the configuration package', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('APPLIED', 'Applied'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='config_pack_created_a0724b_idx'), models.Index(fields=['system_id'], name='config_pack_system__723fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfigPackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('table_name', models.CharField(help_text='Name of the table', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the table configuration', null=True)),
                ('data', models.JSONField(default=list)),
                ('field_config', models.JSONField(default=dict, help_text='Field export configuration including primary, default, and custom fields')),
                ('package_code', models.ForeignKey(db_column='package_code', on_delete=django.db.models.deletion.CASCADE, to='config_packages.configpackage')),
                ('table_id', models.ForeignKey(help_text='Reference to the table object', limit_choices_to={'object_type': 'Table'}, on_delete=django.db.models.deletion.CASCADE, to='base.objects')),
            ],
            options={
                'unique_together': {('package_code', 'table_id')},
            },
        ),
    ]
