# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(editable=False, help_text='Auto-generated resource code (e.g., RES-XXX-0001)', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the resource (e.g., Jane Doe - Master Stylist)', max_length=100, verbose_name='Name')),
                ('resource_type', models.CharField(choices=[('person', 'Person'), ('equipment', 'Equipment'), ('space', 'Space')], help_text='Type of resource: person, equipment, or space', max_length=10, verbose_name='Resource Type')),
                ('base_unit', models.CharField(choices=[('HOUR', 'Hour'), ('MINUTE', 'Minute'), ('DAY', 'Day'), ('SESSION', 'Session')], default='HOUR', help_text='Unit of measurement for this resource', max_length=10, verbose_name='Base Unit')),
                ('direct_unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Pure direct cost (e.g., labor rate, machine cost per unit)', max_digits=10, verbose_name='Direct Unit Cost')),
                ('indirect_cost_pct', models.DecimalField(decimal_places=2, default=0, help_text='Overhead percentage (rent, utilities, admin, etc.)', max_digits=5, verbose_name='Indirect Cost %')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: Direct Unit Cost + (Direct Unit Cost × Indirect Cost %)', max_digits=10, verbose_name='Unit Cost')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit (what customer pays)', max_digits=10, verbose_name='Unit Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resource is currently active', verbose_name='Is Active')),
                ('blocked', models.BooleanField(default=False, help_text='Whether this resource is blocked from use', verbose_name='Blocked')),
                ('description', models.TextField(blank=True, help_text='Additional details about this resource', null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the resource', null=True, upload_to='resources/photos/', verbose_name='Photo')),
                ('dimension_1', models.ForeignKey(blank=True, help_text='Dimension for multi-branch companies (e.g., which branch this resource belongs to)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='dimension.dimensionvalue', verbose_name='Dimension (Branch/Location)')),
                ('general_product_posting_group', models.ForeignKey(blank=True, help_text='General product posting group for accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.generalproductpostinggroup', verbose_name='General Product Posting Group')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='resources_r_code_47c253_idx'), models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'), models.Index(fields=['is_active'], name='resources_r_is_acti_cf90e4_idx'), models.Index(fields=['dimension_1'], name='resources_r_dimensi_a67461_idx')],
            },
        ),
    ]
