# Generated by Django 5.1.7 on 2026-01-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_r_dimensi_a67461_idx',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='dimension_1',
        ),
    ]
