# Generated by Django 5.1.7 on 2026-01-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_itemjournal_calculated_quantity_and_more'),
        ('resources', '0004_resource_base_unit_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement for this resource (same model as items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_using_as_base', to='items.unitofmeasure', verbose_name='Base Unit'),
        ),
    ]
