# Generated by Django 5.1.7 on 2026-01-29 20:33

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_itemjournal_calculated_quantity_and_more'),
        ('resources', '0005_alter_resource_base_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('entry_type', models.CharField(choices=[('Usage', 'Usage'), ('Sale', 'Sale'), ('Positive_Adjustment', 'Positive Adjustment'), ('Negative_Adjustment', 'Negative Adjustment')], help_text='Usage, Sale, or Adjustment', max_length=50, verbose_name='Entry Type')),
                ('document_no', models.CharField(db_index=True, help_text='Document number (e.g. invoice no, journal batch no)', max_length=255, verbose_name='Document No.')),
                ('posting_date', models.DateField(db_index=True, verbose_name='Posting Date')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('work_type', models.CharField(blank=True, help_text='Optional work type code', max_length=50, null=True, verbose_name='Work Type')),
                ('quantity', models.DecimalField(decimal_places=5, default=0, help_text='Quantity in the line UOM', max_digits=18, verbose_name='Quantity')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Cost')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Price')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Unit Price')),
                ('source_type', models.CharField(choices=[('Document', 'Document'), ('Journal', 'Journal')], default='Document', max_length=50, verbose_name='Source Type')),
                ('source_no', models.CharField(blank=True, help_text='Source document or journal number', max_length=255, null=True, verbose_name='Source No.')),
                ('qty_per_unit_of_measure', models.DecimalField(decimal_places=5, default=1, help_text='Conversion to base UOM (e.g. 1 for HOUR, 60 for MINUTE when base is HOUR)', max_digits=18, verbose_name='Qty. per Unit of Measure')),
                ('quantity_base', models.DecimalField(decimal_places=5, default=0, help_text='Quantity expressed in resource base unit', max_digits=18, verbose_name='Quantity (Base)')),
                ('resource', models.ForeignKey(help_text='Resource No.', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='resources.resource', verbose_name='Resource')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_ledger_entries', to='items.unitofmeasure', verbose_name='Unit of Measure Code')),
            ],
            options={
                'verbose_name': 'Resource Ledger Entry',
                'verbose_name_plural': 'Resource Ledger Entries',
                'ordering': ['-posting_date', '-created_at'],
                'indexes': [models.Index(fields=['posting_date'], name='resources_r_posting_fd54b8_idx'), models.Index(fields=['document_no'], name='resources_r_documen_89f129_idx'), models.Index(fields=['resource', 'posting_date'], name='resources_r_resourc_f2a49a_idx')],
            },
        ),
    ]
