# Generated by Django 5.1.7 on 2025-12-12 02:59

import prepayment.models
import utils.utils
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document No.')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('document_date', models.DateField(default=prepayment.models.get_today)),
                ('posting_date', models.DateField(default=prepayment.models.get_today)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('total_prepayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Prepayment Collected')),
                ('total_prepayment_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Prepayment Invoiced')),
                ('total_prepayment_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Prepayment Deducted')),
                ('total_prepayment_to_deduct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of invoiced prepayment to apply next', max_digits=15, verbose_name='Prepmt. Amt. to Deduct')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated percentage based on deposit amount vs document total', max_digits=7, verbose_name='Prepmt. Line Amount %')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_transaction_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Preayment',
                'verbose_name_plural': 'Preayments',
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreaymentInstallmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Editable draft installment not yet collected.', max_digits=15, verbose_name='Draft Installment Amount')),
            ],
            options={
                'verbose_name': 'Preayment Installment Draft',
                'verbose_name_plural': 'Preayment Installment Drafts',
            },
        ),
        migrations.CreateModel(
            name='PreaymentInstallmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Applied Installment Amount')),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Preayment Installment History',
                'verbose_name_plural': 'Preayment Installment Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('tracking_code', models.CharField(blank=True, help_text='Optional tracking/lot reference associated with this prepayment line.', max_length=128, null=True, verbose_name='Tracking Code')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from customer for this prepayment line', max_digits=15, verbose_name='Prepmt. Line Amount')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated percentage based on deposit amount vs line total', max_digits=7, verbose_name='Prepmt. Line Amount %')),
                ('prepayment_amount_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Portion of the deposit already invoiced', max_digits=15, verbose_name='Prepmt. Amt. Inv.')),
                ('prepayment_amount_to_deduct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of invoiced prepayment to apply next', max_digits=15, verbose_name='Prepmt Amt to Deduct')),
                ('prepayment_amount_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative prepayment applied to final invoices', max_digits=15, verbose_name='Prepmt Amt Deducted')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Enter the additional deposit collected for this line; it will be added to the Prepmt. Line Amount when you save.', max_digits=15, null=True, verbose_name='New Installment')),
            ],
            options={
                'verbose_name': 'Preayment Line',
                'verbose_name_plural': 'Preayment Lines',
            },
        ),
        migrations.CreateModel(
            name='PreaymentLineInstallmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Editable draft installment not yet collected.', max_digits=15, verbose_name='Draft Installment Amount')),
            ],
            options={
                'verbose_name': 'Preayment Line Installment Draft',
                'verbose_name_plural': 'Preayment Line Installment Drafts',
            },
        ),
        migrations.CreateModel(
            name='PreaymentLineInstallmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Applied Installment Amount')),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Preayment Line Installment History',
                'verbose_name_plural': 'Preayment Line Installment Histories',
            },
        ),
    ]
