# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_initial'),
        ('prepayment', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayment_documents', to='sales.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='preayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_prepayment_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaymentinstallmentdraft',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_draft', to='prepayment.preayment', verbose_name='Prepayment Document'),
        ),
        migrations.AddField(
            model_name='preaymentinstallmentdraft',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prepayment_document_installment_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaymentinstallmenthistory',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_prepayment_document_installment_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaymentinstallmenthistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_history', to='prepayment.preayment', verbose_name='Prepayment Document'),
        ),
        migrations.AddField(
            model_name='preaymentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='prepayment.preayment', verbose_name='Preayment Document'),
        ),
        migrations.AddField(
            model_name='preaymentline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_lines', to='items.item'),
        ),
        migrations.AddField(
            model_name='preaymentline',
            name='item_unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemuom_prepayment_lines', to='items.itemunitofmeasure'),
        ),
        migrations.AddField(
            model_name='preaymentline',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitofmeasure_prepayment_lines', to='items.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='preaymentlineinstallmentdraft',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_draft', to='prepayment.preaymentline', verbose_name='Prepayment Line'),
        ),
        migrations.AddField(
            model_name='preaymentlineinstallmentdraft',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prepayment_installment_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaymentlineinstallmenthistory',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_prepayment_installment_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preaymentlineinstallmenthistory',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_history', to='prepayment.preaymentline', verbose_name='Prepayment Line'),
        ),
    ]
