# Generated by Django 5.1.7 on 2025-12-12 02:59

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimension', '0001_initial'),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('bom_code', models.CharField(editable=False, help_text='Auto-generated BOM code (e.g., BOM-XXX-0001)', max_length=20, unique=True, verbose_name='BOM Code')),
                ('name', models.CharField(help_text='Name of this BOM', max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('new', 'New'), ('certified', 'Certified'), ('under_development', 'Under Development'), ('closed', 'Closed')], default='new', help_text='Status of the BOM', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this BOM is currently active', verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this BOM', null=True, verbose_name='Notes')),
                ('unit_of_measure', models.ForeignKey(blank=True, help_text='Unit of measure for this BOM (e.g., PCS, HOUR, KG)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unitofmeasure', verbose_name='Unit of Measure Code')),
            ],
            options={
                'verbose_name': 'Production BOM',
                'verbose_name_plural': 'Production BOMs',
                'ordering': ['bom_code'],
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('line_number', models.IntegerField(blank=True, help_text='Sequence number for this line', null=True, verbose_name='Line Number')),
                ('line_type', models.CharField(choices=[('item', 'Item'), ('production_bom', 'Production BOM')], help_text='Type of line: item or production bom', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, help_text='Description of the item or resource', max_length=200, verbose_name='Description')),
                ('quantity_per', models.DecimalField(decimal_places=3, default=0, help_text='Quantity required per unit of the parent item', max_digits=8, verbose_name='Quantity per')),
                ('scrap_pct', models.DecimalField(decimal_places=2, default=0, help_text='Scrap percentage (0-100)', max_digits=5, verbose_name='Scrap %')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Cost per unit (auto-calculated)', max_digits=10, verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total cost for this line (auto-calculated)', max_digits=10, verbose_name='Total Cost')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this line', null=True, verbose_name='Notes')),
                ('item', models.ForeignKey(blank=True, help_text='Item number (for inventory items) or Resource (for resource lines)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines_as_item', to='items.item', verbose_name='No.')),
                ('unit_of_measure', models.ForeignKey(blank=True, help_text='Unit of measure (e.g., PCS, HOUR, KG)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unitofmeasure', verbose_name='Unit of Measure Code')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionbom', verbose_name='BOM')),
            ],
            options={
                'verbose_name': 'BOM Line',
                'verbose_name_plural': 'BOM Lines',
                'ordering': ['bom', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('no', models.CharField(editable=False, help_text='Auto-generated production order number (e.g., PROD-XXX-0001)', max_length=20, unique=True, verbose_name='No.')),
                ('name', models.CharField(help_text='Name of this production order', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the production order', null=True, verbose_name='Description')),
                ('source_type', models.CharField(choices=[('item', 'Item'), ('production_bom', 'Production BOM')], default='item', help_text='Type of source: item or production bom', max_length=20, verbose_name='Source Type')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity to produce', max_digits=10, verbose_name='Quantity')),
                ('blocked', models.BooleanField(default=False, help_text='Whether this production order is blocked', verbose_name='Blocked')),
                ('source_no', models.ForeignKey(help_text='Item number for this production order', on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='items.item', verbose_name='Source No.')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of this production order line', max_length=20, verbose_name='Status')),
                ('description', models.CharField(blank=True, help_text='Description of this production order line', max_length=200, null=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity to produce', max_digits=10, verbose_name='Quantity')),
                ('finished_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity that has been finished', max_digits=10, verbose_name='Finished Quantity')),
                ('start_date', models.DateField(blank=True, help_text='Start date for production', null=True, verbose_name='Start Date')),
                ('ending_date', models.DateField(blank=True, help_text='Ending date for production', null=True, verbose_name='Ending Date')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10, verbose_name='Unit Cost')),
                ('dimension_1', models.ForeignKey(blank=True, help_text='Dimension 1 value', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines_dimension_1', to='dimension.dimensionvalue', verbose_name='Dimension 1')),
                ('location_code', models.ForeignKey(blank=True, help_text='Location code for this production order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines', to='items.location', verbose_name='Location Code')),
                ('production_bom_no', models.ForeignKey(blank=True, help_text='Production BOM used for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines', to='production.productionbom', verbose_name='Production BOM No.')),
                ('production_order', models.ForeignKey(help_text='Parent production order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionorder', verbose_name='Production Order')),
                ('unit_of_measure_code', models.ForeignKey(blank=True, help_text='Unit of measure code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines', to='items.unitofmeasure', verbose_name='Unit of Measure Code')),
            ],
            options={
                'verbose_name': 'Production Order Line',
                'verbose_name_plural': 'Production Order Lines',
                'ordering': ['production_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productionbom',
            index=models.Index(fields=['bom_code'], name='production__bom_cod_91ee50_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbom',
            index=models.Index(fields=['is_active'], name='production__is_acti_d6cc85_idx'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['bom'], name='production__bom_id_b431fa_idx'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['line_type'], name='production__line_ty_cbd9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bomline',
            index=models.Index(fields=['item'], name='production__item_id_d351f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bomline',
            unique_together={('bom', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['no'], name='production__no_a5677d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['source_type'], name='production__source__3ea58a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['source_no'], name='production__source__873b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['blocked'], name='production__blocked_26a7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['production_order'], name='production__product_2c5fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['status'], name='production__status_4ce947_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['location_code'], name='production__locatio_6a7c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['production_bom_no'], name='production__product_49e48a_idx'),
        ),
    ]
