# Generated by Django 5.1.7 on 2025-12-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimension', '0001_initial'),
        ('items', '0005_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderline',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for this production order line', null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='productionorderline',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Item number for this production order line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines', to='items.item', verbose_name='Item No.'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['item'], name='production__item_id_1e3986_idx'),
        ),
    ]
