# Generated by Django 5.1.7 on 2025-12-21 02:26

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_initial'),
        ('production', '0002_add_item_and_due_date_to_production_order_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('finished', 'Finished')], default='planned', help_text='Status of this component', max_length=20, verbose_name='Status')),
                ('item_name', models.CharField(blank=True, help_text='Item name (auto-filled from item)', max_length=200, null=True, verbose_name='Item Name')),
                ('description', models.CharField(blank=True, help_text='Description (auto-filled from item name)', max_length=200, null=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Quantity required', max_digits=10, verbose_name='Quantity')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Expected quantity to be consumed', max_digits=10, verbose_name='Expected Quantity')),
                ('quantity_per', models.DecimalField(decimal_places=3, default=0, help_text='Quantity required per unit of finished product', max_digits=8, verbose_name='Quantity per')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10, verbose_name='Unit Cost')),
                ('item', models.ForeignKey(blank=True, help_text='Component item number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_components', to='items.item', verbose_name='Item No.')),
                ('location_code', models.ForeignKey(blank=True, help_text='Location code for this component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_components', to='items.location', verbose_name='Location Code')),
                ('production_order', models.ForeignKey(help_text='Parent production order', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.productionorder', verbose_name='Production Order')),
                ('production_order_line', models.ForeignKey(blank=True, help_text='Production order line this component belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.productionorderline', verbose_name='Production Order Line')),
                ('unit_of_measure_code', models.ForeignKey(blank=True, help_text='Unit of measure code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_components', to='items.unitofmeasure', verbose_name='Unit of Measure Code')),
            ],
            options={
                'verbose_name': 'Production Order Component',
                'verbose_name_plural': 'Production Order Components',
                'ordering': ['production_order', 'id'],
                'indexes': [models.Index(fields=['production_order'], name='production__product_6cdcbc_idx'), models.Index(fields=['production_order_line'], name='production__product_cf161d_idx'), models.Index(fields=['status'], name='production__status_52975b_idx'), models.Index(fields=['item'], name='production__item_id_a2e39c_idx'), models.Index(fields=['location_code'], name='production__locatio_b3f5fb_idx')],
            },
        ),
    ]
