# Generated by Django 5.1.7 on 2025-12-23 03:30

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_add_production_order_to_item_journal'),
        ('production', '0003_add_production_order_component'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Machine center code (e.g., MC-001)', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the machine center', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the machine center', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this machine center is currently active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Machine Center',
                'verbose_name_plural': 'Machine Centers',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='production__code_61bd88_idx'), models.Index(fields=['is_active'], name='production__is_acti_cecf13_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Work center code (e.g., WC-001)', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the work center', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the work center', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this work center is currently active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Work Center',
                'verbose_name_plural': 'Work Centers',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='production__code_e654f5_idx'), models.Index(fields=['is_active'], name='production__is_acti_ea980e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapacityLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('no', models.CharField(help_text='Code reference to Work Center, Machine Center, or Resource based on Type', max_length=20, verbose_name='No.')),
                ('posting_date', models.DateField(help_text='Date when the capacity was used', verbose_name='Posting Date')),
                ('type', models.CharField(choices=[('work_center', 'Work Center'), ('machine_center', 'Machine Center'), ('resource', 'Resource')], help_text='Type of capacity: Work Center, Machine Center, or Resource', max_length=20, verbose_name='Type')),
                ('document_no', models.CharField(help_text='Document number for this capacity entry', max_length=255, verbose_name='Document No.')),
                ('description', models.TextField(blank=True, help_text='Description of the capacity usage', null=True, verbose_name='Description')),
                ('operation_no', models.CharField(blank=True, help_text='Operation number', max_length=20, null=True, verbose_name='Operation No.')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity of capacity used', max_digits=10, verbose_name='Quantity')),
                ('setup_time', models.DecimalField(decimal_places=2, default=0, help_text='Setup time in hours', max_digits=10, verbose_name='Setup Time')),
                ('run_time', models.DecimalField(decimal_places=2, default=0, help_text='Run time in hours', max_digits=10, verbose_name='Run Time')),
                ('stop_time', models.DecimalField(decimal_places=2, default=0, help_text='Stop time in hours', max_digits=10, verbose_name='Stop Time')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity of output produced', max_digits=10, verbose_name='Output Quantity')),
                ('order_type', models.CharField(choices=[('production', 'Production')], default='production', help_text='Type of order (currently only Production)', max_length=20, verbose_name='Order Type')),
                ('cap_unit_of_measure_code', models.ForeignKey(blank=True, help_text='Unit of measure for capacity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unitofmeasure', verbose_name='Cap. Unit of Measure Code')),
                ('item_no', models.ForeignKey(blank=True, help_text='Item that caused this capacity consumption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='items.item', verbose_name='Item No.')),
                ('order_line_no', models.ForeignKey(blank=True, help_text='Production order line that caused this capacity consumption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='production.productionorderline', verbose_name='Order Line No.')),
                ('order_no', models.ForeignKey(blank=True, help_text='Production order that caused this capacity consumption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='production.productionorder', verbose_name='Order No.')),
                ('resource', models.ForeignKey(blank=True, help_text='Resource used (if type is Resource)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='resources.resource', verbose_name='Resource')),
                ('machine_center', models.ForeignKey(blank=True, help_text='Machine center used (if type is Machine Center)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='production.machinecenter', verbose_name='Machine Center')),
                ('work_center', models.ForeignKey(blank=True, help_text='Work center used (if type is Work Center)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_ledger_entries', to='production.workcenter', verbose_name='Work Center')),
            ],
            options={
                'verbose_name': 'Capacity Ledger Entry',
                'verbose_name_plural': 'Capacity Ledger Entries',
                'ordering': ['-posting_date', '-created_at'],
                'indexes': [models.Index(fields=['posting_date'], name='production__posting_8f9b68_idx'), models.Index(fields=['type'], name='production__type_9d717e_idx'), models.Index(fields=['order_no'], name='production__order_n_6474d0_idx'), models.Index(fields=['order_line_no'], name='production__order_l_679d49_idx'), models.Index(fields=['item_no'], name='production__item_no_569c70_idx')],
            },
        ),
    ]
