# Generated by Django 5.1.7 on 2025-12-23 05:47

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_inventorypostingsetup_wip_account'),
        ('production', '0004_add_capacity_ledger_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='general_prod_posting_group',
            field=models.ForeignKey(blank=True, help_text='General product posting group for this work center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centers', to='postings.generalproductpostinggroup', verbose_name='General Prod. Posting Group'),
        ),
        migrations.CreateModel(
            name='CapacityUnitOfMeasure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Capacity unit of measure code (e.g., HOURS, MINUTES)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('description', models.CharField(help_text='Description of the capacity unit of measure', max_length=100, verbose_name='Description')),
                ('type', models.CharField(choices=[('Milliseconds', 'Milliseconds'), ('100/Hour', '100/Hour'), ('Minutes', 'Minutes'), ('Hours', 'Hours'), ('Days', 'Days'), ('Seconds', 'Seconds')], help_text='Type of capacity unit (Milliseconds, Minutes, Hours, Days, Seconds, 100/Hour)', max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Capacity Unit of Measure',
                'verbose_name_plural': 'Capacity Units of Measure',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='production__code_5be6db_idx'), models.Index(fields=['type'], name='production__type_66292d_idx')],
            },
        ),
        migrations.AddField(
            model_name='workcenter',
            name='unit_of_measure_code',
            field=models.ForeignKey(blank=True, help_text='Unit of measure code for capacity calculations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centers', to='production.capacityunitofmeasure', verbose_name='Capacity Unit of Measure Code'),
        ),
    ]
