# Generated by Django 5.1.7 on 2025-12-23 07:55

import django.db.models.deletion
import utils.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_workcenter_general_prod_posting_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(editable=False, help_text='Auto-generated work center code (e.g., WORKCTR-000001)', max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='ShopCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('code', models.CharField(help_text='Shop calendar code (e.g., STANDARD, SHIFT1)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('description', models.CharField(help_text='Description of the shop calendar', max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Shop Calendar',
                'verbose_name_plural': 'Shop Calendars',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='production__code_d5ddf2_idx')],
            },
        ),
        migrations.AddField(
            model_name='workcenter',
            name='shop_calendar_code',
            field=models.ForeignKey(blank=True, help_text='Shop calendar for scheduling this work center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centers', to='production.shopcalendar', verbose_name='Shop Calendar Code'),
        ),
        migrations.CreateModel(
            name='ShopCalendarHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('starting_date_time', models.DateTimeField(help_text='Starting date and time for this holiday', verbose_name='Starting Date-Time')),
                ('ending_time', models.TimeField(help_text='Ending time for this holiday', verbose_name='Ending Time')),
                ('description', models.CharField(blank=True, help_text='Description of the holiday', max_length=255, null=True, verbose_name='Description')),
                ('shop_calendar', models.ForeignKey(help_text='Shop calendar this holiday belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='production.shopcalendar', verbose_name='Shop Calendar')),
            ],
            options={
                'verbose_name': 'Shop Calendar Holiday',
                'verbose_name_plural': 'Shop Calendar Holidays',
                'ordering': ['shop_calendar', 'starting_date_time'],
                'indexes': [models.Index(fields=['shop_calendar', 'starting_date_time'], name='production__shop_ca_365d8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopCalendarWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('system_id', utils.utils.UUIField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='System ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week', max_length=10, verbose_name='Day')),
                ('starting_time', models.TimeField(help_text='Starting time for this working day (e.g., 08:00:00)', verbose_name='Starting Time')),
                ('ending_time', models.TimeField(help_text='Ending time for this working day (e.g., 16:00:00)', verbose_name='Ending Time')),
                ('work_shift_code', models.CharField(blank=True, help_text='Work shift code (e.g., 1, 2, 3)', max_length=10, null=True, verbose_name='Work Shift Code')),
                ('shop_calendar', models.ForeignKey(help_text='Shop calendar this working day belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='production.shopcalendar', verbose_name='Shop Calendar')),
            ],
            options={
                'verbose_name': 'Shop Calendar Working Day',
                'verbose_name_plural': 'Shop Calendar Working Days',
                'ordering': ['shop_calendar', 'day', 'starting_time'],
                'indexes': [models.Index(fields=['shop_calendar', 'day'], name='production__shop_ca_cbe770_idx'), models.Index(fields=['shop_calendar', 'starting_time'], name='production__shop_ca_4dd38b_idx')],
                'unique_together': {('shop_calendar', 'day', 'starting_time', 'work_shift_code')},
            },
        ),
    ]
