# Generated by Django 5.1.7 on 2025-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_workcenter_code_shopcalendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='capacity',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Capacity of the work center', max_digits=18, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='direct_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Direct unit cost for this work center', max_digits=18, null=True, verbose_name='Direct Unit Cost'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Unit cost for this work center', max_digits=18, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='unit_cost_calculation',
            field=models.CharField(blank=True, choices=[('Units', 'Units'), ('Time', 'Time')], help_text='Unit cost calculation method: Units or Time', max_length=10, null=True, verbose_name='Unit Cost Calculation'),
        ),
    ]
