# Generated by Django 5.1.7 on 2026-02-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_itemjournal_calculated_quantity_and_more'),
        ('production', '0008_rename_source_no_to_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productionorder',
            name='production__source__873b5e_idx',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('released', 'Released'), ('finished', 'Finished')], default='released', help_text='Status of the production order', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(help_text='Item to produce (must have a Production BOM)', on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='items.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='productionorderline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of this production order line', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['item'], name='production__item_id_a6e0de_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='production__status_b4dbe1_idx'),
        ),
    ]
