# Generated by Django 5.1.7 on 2026-02-27 18:25

import django.db.models.deletion
from django.db import migrations, models


def _pg_column_exists(cursor, relname, attname):
    cursor.execute(
        """
        SELECT 1
        FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        JOIN pg_namespace n ON c.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND c.relname = %s
          AND a.attname = %s
          AND a.attnum > 0
          AND NOT a.attisdropped
        """,
        [relname, attname],
    )
    return cursor.fetchone() is not None


def migrate_dimension_column(apps, schema_editor):
    """
    Move production_productionorderline.dimension_1_id -> global_dimension_1_id when needed.
    Handles tenants where global_dimension_1_id was added manually.
    """
    table = "production_productionorderline"
    with schema_editor.connection.cursor() as cursor:
        has_old = _pg_column_exists(cursor, table, "dimension_1_id")
        has_new = _pg_column_exists(cursor, table, "global_dimension_1_id")
        if has_old and not has_new:
            cursor.execute(
                f"""
                ALTER TABLE {table}
                RENAME COLUMN dimension_1_id TO global_dimension_1_id
                """
            )
        elif has_old and has_new:
            cursor.execute(f"ALTER TABLE {table} DROP COLUMN dimension_1_id CASCADE")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dimension", "0004_add_dimension_set_models"),
        ("production", "0010_add_dimension_set_to_ledger_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="productionorderline",
                    name="dimension_1",
                ),
                migrations.AddField(
                    model_name="productionorderline",
                    name="global_dimension_1",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Global Dimension 1 value",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_order_lines_global_dimension_1",
                        to="dimension.dimensionvalue",
                        verbose_name="Global Dimension 1",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(migrate_dimension_column, noop_reverse),
            ],
        ),
    ]
